### ISSUE TITLE
Lokal nicht ausführbar 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/rexstan#11]
Hi,

wenn ich das AddOn lokal (MAMP) nutzen möchte kommt folgende Fehler:

![image](https://user-images.githubusercontent.com/330516/173289328-fdbefbef-ab77-44d7-bfa6-5db2f595d1a6.png)

Die PHP Storm Integration funktioniert prima. Reicht aktuell zum testen (DANKE!).

Oliver

**Comment by staabm** [comment]
von seiten des addons kann man an diesem fehler nix tun
