### ISSUE TITLE
phpstan-dba.neon is missing

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/rexstan#126]
Gerade Rexstan über den Installer aktualisiert und jetzt im PHPStorm die Meldung:
File ..../redaxo/src/addons/rexstan/lib/phpstan-dba.neon is mission or is not readable.

**Comment by marcohanke** [comment]
In PHPstan? Da kommt nix.
Der Fehler wird mir in PHPStorm als Modal eingeblen
![Bildschirmfoto 2022-09-21 um 12 57 07](https://user-images.githubusercontent.com/2425981/191487284-c4cb050f-5bcf-4f5a-8095-e89b8747838a.png)
![Bildschirmfoto 2022-09-21 um 12 57 17](https://user-images.githubusercontent.com/2425981/191487287-868f08b0-0951-4aec-9881-e33f751be708.png)
det

**Comment by marcohanke** [comment]
Wo soll der Hinweis kommen? In PHPStorm in den Einstellungen?
Da kam nix.
Der Hinweis kommt als Model in PHPStorm

![Bildschirmfoto 2022-09-21 um 12 57 17](https://user-images.githubusercontent.com/2425981/191487525-287910e6-c7b4-4e1f-a750-03b17151ac92.png)
![Bildschirmfoto 2022-09-21 um 12 57 07](https://user-images.githubusercontent.com/2425981/191487531-f51ba8e9-20a9-4a72-b0bc-ef18cc6b106c.png)

**Comment by staabm** [comment]
In der rexstan Oberfläche

**Comment by marcohanke** [comment]
Da war ich nachdem Update noch gar nicht. Bin gerade drauf, phpstan-dba war nicht aktiv. Ich habs jetzt aktiviert, Fehler bleibt bestehen.

![Bildschirmfoto 2022-09-21 um 13 03 20](https://user-images.githubusercontent.com/2425981/191488203-094a3deb-202b-4abf-83c0-f479f64ef252.png)

**Comment by staabm** [comment]
Kommt der fehler auch in der web Analyse?

**Comment by marcohanke** [comment]
Nein, nur im PHPStorm, ich hab die Datei jetzt angelegt, dann läuft scheinbar alles

**Comment by staabm** [comment]
die datei wurde eigentlich nach `config/` verschoben und dort sollte er sie auch suchen.

https://github.com/FriendsOfREDAXO/rexstan/blob/5d14ef7ef7229d3c5bb2217e703d9fdcb8d33bc5/config/phpstan-dba.neon

ggf. cached phpstorm eine veraltete config irgendwo

**Comment by marcohanke** [comment]
Ich hatte die Config noch mal resetet und neu eingetragen und paralell die Datei händisch angelegt. Danch war der Fehler weg. 
Ich dachte es lag an der manuellen Datei, die war aber leer, ich hab sie gelöscht und es läuft immernoch.
Scheint wirklich ein Caching Ding zu sein.

**Comment by staabm** [comment]
grad nochmal getestet. der erwartete fehler kommt auf der Web UI Analyse seite - nicht wie urspr. gedacht in der Einstellungen seite

<img width="1234" alt="grafik" src="https://user-images.githubusercontent.com/120441/192110267-0436ed5a-9c77-4147-bf8c-ac67c59233b3.png">
