### ISSUE TITLE
**Exception:** Could not analyze baseline

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/rexstan#142]
Summary wirft n Whoops

**Exception:** Could not analyze baseline
**File:** redaxo/src/addons/rexstan/pages/summary.php
**Line:** 7

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                      | Line     |
| -------------------------------------------- | ----------------------------------------- | -------- |
| require                                      | redaxo/src/core/lib/packages/package.php  | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php     | 489      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php        | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php     | 490      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php     | 439      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/rexstan/pages/index.php | 7        |
| require                                      | redaxo/src/core/lib/packages/package.php  | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php     | 489      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php        | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php     | 490      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php     | 422      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php               | 239      |
| require                                      | redaxo/src/core/boot.php                  | 143      |
| require                                      | redaxo/index.php                          | 9        |

</details>
<details>
<summary>System report (REDAXO 5.14.1, PHP 8.0.19, MariaDB 10.8.3)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.0.19                         |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 10.8.3 |
| Character set | utf8mb4        |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.53  |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.0 |
|      Protocol | HTTP/1.1    |
|         HTTPS | no          |

| Packages          |            |
| ----------------: | :--------- |
|            backup | 2.8.2      |
|          be_style | 3.1.0      |
|   be_style/redaxo | 3.1.0      |
|           install | 2.10.0     |
|       maintenance | 2.8.5      |
|     media_manager | 2.13.0     |
|         mediapool | 2.12.0     |
|          metainfo | 2.9.0      |
|           minibar | 2.3.1      |
|         phpmailer | 2.11.2     |
|           project | dev        |
|  quick_navigation | 6.0.0      |
|           rexstan | 1.0.47     |
|         structure | 2.14.1     |
| structure/content | 2.14.1     |
|             users | 2.9.0      |
|             yform | 4.0.2      |
|       yform/email | 4.0.2      |
|     yform/manager | 4.0.2      |
|  yform_quick_edit | 1.0.1      |

</details>

**Comment by staabm** [comment]
danke für den report.

passiert das in einem system wo die "web ui" selbst funktioniert?

**Comment by skerbis** [comment]
ja

**Comment by staabm** [comment]
hab einen fix geraten.. falls das problem noch besteht, gerne wiedereröffnen
