### ISSUE TITLE
Abfrage "('rex_' != rex::getTablePrefix())" "is always true"?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#143]
In der install.php des Geolocation-Addons wird geprüft, ob in der Redaxo-Instanz wider Erwarten ein anderes DB-Prefix als "rex_" eingestellt ist. Das wird mit 99,99% gefühlter Wahrscheinlich nicht der Fall sein, aber sei´s drum.

https://github.com/christophboecker/geolocation/blob/57f164af86654479f3ad4b0430681bd553c860c8/install.php#L129

```php
if ('rex_' != rex::getTablePrefix()) {
```
Dazu sagt RexStan: 
```
If condition is always true.
```
Das ist in der Grundsätzlichkeit nicht zutreffend, nur eben auf dem System, auf dem ich teste. Liegt das nun an phpstan oder kommt das aus der Anpassung an Redaxo? Und ist es Bug oder Feature?

**Affected versions / Verwendete Versionen**

REDAXO:  5.14.2
rexstan: 1.0.47

**Comment by staabm** [comment]
danke für den report.

ist ein false-positive, der entsteht wenn phpstan-dba aktiv ist.

muss ich auf rexstan seite beheben

**Comment by staabm** [comment]
Memo an mich: ggf mit phpstandba-inference-placeholder lösbar
