### ISSUE TITLE
Umgang mit einen Pathprovidern

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/rexstan#147]
Wir haben eine eigene Ordnerstruktur, die in den index.php Dateien im Frontend und Backend individuell eingetragen ist,

![Bildschirmfoto 2022-09-29 um 16 15 17](https://user-images.githubusercontent.com/322951/193055682-dc59a357-7505-4b91-a23f-0660b0f4ab57.png)

Frontendindex liegt in public/index.php

```
<?php

unset($REX);
$REX['REDAXO'] = false;
$REX['HTDOCS_PATH'] = './';
$REX['BACKEND_FOLDER'] = 'redaxo';
$REX['LOAD_PAGE'] = true;

require __DIR__.'/../src/path_provider.php';
$REX['PATH_PROVIDER'] = new app_path_provider();

require $REX['PATH_PROVIDER']->core('boot.php');
```

backendindex.php liegt demnach in public/redaxo/index.php

```
<?php

unset($REX);
$REX['REDAXO'] = true;
$REX['HTDOCS_PATH'] = '../';
$REX['BACKEND_FOLDER'] = 'redaxo';
$REX['LOAD_PAGE'] = true;

require __DIR__.'/../../src/path_provider.php';
$REX['PATH_PROVIDER'] = new app_path_provider();

require $REX['PATH_PROVIDER']->core('boot.php');
```

Konnte ich nur umgehen, indem ich in der phpstan-bootstrap.php die entsprechenden Änderungen gemacht habe. Wie könnte man das dauerhaft individuell lösen? Wenn du einen Ansatz hast, kann ich einen PR einreichen.

**Comment by staabm** [comment]
stand heute ist das hier der stand bzgl. path provider

https://github.com/FriendsOfREDAXO/rexstan/blob/1ceaf796be5fa2035b2edac904870a1be16434af/install.php#L5-L8

bzgl einem möglichen pfad was man tun muss/kann um es zu erreichen muss ich mir gedanken machen

**Comment by dergel** [comment]
huch .. die Meldung kann bei mir nicht .. es wurde nur einfach die boot Dateien des Cores nicht gefunden und entsprechend als Warung ausgespuckt. Wenn mir was gutes einfällt melde ich mich.

**Comment by staabm** [comment]
> Konnte ich nur umgehen, indem ich in der phpstan-bootstrap.php die entsprechenden Änderungen gemacht habe.

d.h. wie hat die phpstan-bootstrap.php danach ausgesehen?

ich vermute es wäre schwierig PATH_PROVIDER im allgemeinen zu hinterlegen, aber ggf. kann ich das yakamara setup selbst fest integrieren...

**Comment by dergel** [comment]
phpstan_bootstrap.php

hier musst ich diese beiden Variablen ändern, für unseren Fall so:
```

$REX['HTDOCS_PATH'] = realpath(__DIR__.'/../../../');
$REX['BACKEND_FOLDER'] = '';
```

Leider weiß ich nicht, wie ich den PathProvider dort reinbekommen soll, da dieser vor dem Aufruf von core/boot.php aktiviert werden muss. Wir haben die Einbindung in den beiden index.php Dateien im Front und Backend.

In der Backend index.php z.B. so

```
<?php

unset($REX);
$REX['REDAXO'] = true;
$REX['HTDOCS_PATH'] = '../';
$REX['BACKEND_FOLDER'] = 'redaxo';
$REX['LOAD_PAGE'] = true;

require __DIR__.'/../../src/path_provider.php';
$REX['PATH_PROVIDER'] = new app_path_provider();

require $REX['PATH_PROVIDER']->core('boot.php');
```

Der neue Pathprovider sieht so aus.

```
<?php

require_once __DIR__ . '/core/lib/util/path_default_provider.php';

class app_path_provider extends rex_path_default_provider
{
    public function __construct()
    {
        parent::__construct(dirname(__DIR__), 'redaxo', true);
    }

    public function frontend($file)
    {
        return $this->base('public/'.$file);
    }

    public function bin($file)
    {
        return $this->base('bin/' . $file);
    }

    public function data($file)
    {
        return $this->base('var/data/' . $file);
    }

    public function cache($file)
    {
        return $this->base('var/cache/' . $file);
    }

    public function src($file)
    {
        return $this->base('src/' . $file);
    }
}

```
