### ISSUE TITLE
Gratulation, es wurden keine Fehler in Level 9 gefunden -> Kein Medaillen-Icon 

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexstan#167]
Es wird zwar die Meldung

_Gratulation, es wurden keine Fehler in Level 9 gefunden_

und Konfetti angezeigt aber keine Icon Goldmedaille oder sonstiges :)

**Comment by aeberhard** [comment]
Nach dem Konfetti steht die Meldung alleine. Da müsste noch eine tolle SuperTolle-Platin-Medaille ran :)

**Comment by staabm** [comment]
wenn du möchtest, gerne hier https://github.com/FriendsOfREDAXO/rexstan/blob/8c9bcfff370fe519171a24f476bc922266e84177/pages/analysis.php#L48-L108

ich hatte auf level 9 das konfetti statt einem emoji.. aber wenn du ein passendes findest, gerne noch eins rein
