### ISSUE TITLE
false positiv bei SQL-Injection-Analyse?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#172]
**Description / Beschreibung**

Mein Code hat eine Klasse `class mapset extends rex_yform_dataset`. Für diesen Code-Block
```php
$table = mapset::table();
$qry = 'SELECT `id`, `title` FROM `'.$table->getTableName().'` WHERE FIND_IN_SET(:id,`layer`)';
```
erhalte ich die Meldung
```
Possible SQL-injection in expression $table->getTableName().
```
Im Gesamtkontext betrachtet verstehe ich nicht, wie an dieser Stelle Murks in´s SQL gelangen kann. Selbst wenn irgendwo vorher ein Tabellenname mit fiesem Inhalt zum Aktivieren des Dataset benutzt worden wäre, wäre der Tabellenname an der Stelle schon aufgeflogen.   

Sieht ein wenig wie "falsch positiv" aus oder gehört in die Kategorie der Meldungen, die aufgrund von Gesamtkomplexität halt nicht auflösbar sind?

Wenn es ein Bug in der Analyse ist: hiermit gemeldet.
 
Ansonsten kann ich auch gut damit leben. 
  

**Affected versions / Verwendete Versionen**

Rexstan 1.0.51

**Comment by staabm** [comment]
welchen return-type liefert `$table->getTableName()` ? sobald man einen `string` in ein bestehendes sql query verktettet, geht rexstan davon aus, dass es ein potentielles sql injection szenario ist, da rexstan nicht wissen kann, wo dieser string herkommt.

falls das nur der tabellen-name ist, empfiehlt sich mit den redaxo core methoden `rex::getTable()` bzw. `rex::getTablePrefix()` zu arbeiten, da diese für die analyse gewhitelistet sind:
https://github.com/FriendsOfREDAXO/rexstan/blob/4668edc7fa4fc29a4586043098bc407309445f52/lib/rule/RexSqlInjectionRule.php#L207-L209

alternativ kannst du mittels `@psalm-taint-escape sql` die methode `getTableName` in `mapset` annotieren sodass du `rexstan` mitteilst, dass diese methode bzgl. sql injection unbedenkliche werte zurückliefert

**Comment by christophboecker** [comment]
Da komme ich nicht ran, das ist yform. `mapset` erbt `$table` von `rex_yform_manager_dataset` und die Funktion `getTableName()` kommt aus `rex_yform_manager_table`. Danke für´s Feedback.

**Comment by staabm** [comment]
@dergel ist diese methode `rex_yform_manager_table->getTableName()`  dafür gedacht um in sql verwendet zu werden?

falls ja: werden die inhalte dieser variable entsprechend escaped abgesichert?

**Comment by dergel** [comment]
`rex_yform_manager_table->getTableName()` wird auch in Queries verwendet und, soweit ich das sehe, nicht immer escaped (was zu korrgieren ist), aber ausschliesslich Tabellennamen beinhaltet, welche vorher gesichert wurden (Schreibweise..)

**Comment by staabm** [comment]
@dergel wenn sichergestellt ist, dass dort keine ungütligen zeichen drinn sein können (also sql) safe, bräuchte es auch kein escaping.

somit sollte die methode mit `@psalm-taint-escape sql` annotiert werden, was dazu führt dass kein 

> Possible SQL-injection in expression $table->getTableName().

error mehr von rexstan gemeldet wird

**Comment by staabm** [comment]
muss in yform gefixed werde. da bereits ein issue dort geöffnet wurde, mach ich hier zu
