### ISSUE TITLE
statt `register_shutdown_function` besser `'RESPONSE_SHUTDOWN'` empfehlen?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#173]
könnte man "verbieten" analog 

https://github.com/FriendsOfREDAXO/rexstan/blob/4668edc7fa4fc29a4586043098bc407309445f52/config/rex-superglobals.neon#L30-L31

**Comment by aeberhard** [comment]
Ich habe gerade mal versucht 

```
        register_shutdown_function(function() {
            echo '<br><br>' .rex_view::error(rex_addon::get('demo_fullpage')->i18n('compile_error'));
        });
```
durch 

```
        rex_extension::register('RESPONSE_SHUTDOWN', function () {
            echo '<br><br>' .rex_view::error(rex_addon::get('demo_fullpage')->i18n('compile_error'));
        });
```
zu ersetzen. Hat aber nicht zum erwarteten Ergebnis geführt (Ausgabe der Meldung) !?

Gibt es da noch einen besonderen Trick bei diesem EP?

**Comment by staabm** [comment]
in meinen Augen ist es schwierig zur ausgabe mit `register_shutdown_function`  zu arbeiten - ich vermute dass ist code, den du heute irgendwo so hast?

innerhalb von `register_shutdown_function` hat man ja gar keine idee/kontrolle wo diese ausgabe letztendlich landen wird?
unabh. vom eigentlichen issue hier, würde ich in frage stellen ob der bisherige weg über
```
       register_shutdown_function(function() {
            echo '<br><br>' .rex_view::error(rex_addon::get('demo_fullpage')->i18n('compile_error'));
        });
```

überhaupt sinnvoll ist, bzw. was man darüber erreichen will

**Comment by aeberhard** [comment]
Hey Markus,
in meinem Fall wird die Meldung ausgegeben wenn der CSS-Compiler einfach mit exit stirbt.
So sieht man wenigstens etwas :)
Wollte auch nur darauf hinweisen dass `register_shutdown_function` nicht mit dem REDAXO-EP ersetzt werden kann :)

**Comment by staabm** [comment]
Danke passt
