### ISSUE TITLE
Auch inaktive Plugins werden gescannt. Soll das so?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#184]
Irgendwann fiel mir auf, dass der **gesamte** Plugin-Ordner eines Addons mit analysiert wird und nicht nur die aktivierten Plugins. Vermutlich wird hier einfach der Ordner `addon/plugin` eingebunden ähnlich wie `addon/lib`. Bei der Auswahl der Addons werden hingegen nur aktivierte zur Analyse aufgelistet. 

Das lässt sich einfach mit dem Addon be_style prüfen: Plugin "Redaxo" ist installier, Plugin "Customizer" nicht. Dennoch wird Customizer analysiert:
<img width="1035" alt="grafik" src="https://user-images.githubusercontent.com/10065904/196610928-af9ef728-b6ee-437f-a85a-eb22f9c02471.png">

<img width="741" alt="grafik" src="https://user-images.githubusercontent.com/10065904/196610830-18fb504e-a48c-451d-8cda-3a6bda89b513.png">

Mir ist nicht so ganz klar, ob ein Scan eines nicht aktivierten Plugins oder ein Scan unter Einbeziehung eines nicht aktivierten Addons zu verfälschten Ergebnissen kommen kann. Vermutung: eher nicht.

Trotzdem wollte ich mal drauf hingewiesen haben.

**Comment by staabm** [comment]
danke für den hinweis.

ich habe keine konkrete antwort bzw. keine offensichtliche antwort wie es sein soll.

bisher ist es so, dass sobald man ein addon zur analyse aktiviert, alle dateien innerhalb eines addons gescannt werden.
da plugins im addon drinnen liegen werden die also auch gescannt, egal ob aktiv oder nicht.

wenn das bisherige verhalten keine konkreten probleme bringt, würd ich es erstmal so lassen.
ich denke auch dass es "komisch" wäre, wenn man die addons in der rex-stan config verwaltung zur analyse aktiviert, die plugins zu den addons aber dann wiederrum über die addonverwaltung "indirekt" einstellt.
