### ISSUE TITLE
No rex_media found with id 'REX_MEDIA[1]'.

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/rexstan#204]
rexstan Version 1.0.55

Einfach erklärt. Diese Meldung kommt, weil dem Modul nicht klar ist, dass REX_MEDIA[1] ersetzt wird und daher nicht gesagt ist, dass dort wirklich nichts vorhanden ist, oder falsch ist.

Besser wäre es, wenn es hier keine Meldung gibt

**Comment by dergel** [comment]
ich denke ich die gleiche Kerbe schlägt sowas hier:
```

if ('REX_VALUE[4]' != '') {
    $href = 'REX_VALUE[4]';
}
```

-> If condition is always true

**Comment by staabm** [comment]
danke für die infos. @dergel kannst du vollständigere beispiele liefern damit ich den gleichen case-teste wie du meldest?

**Comment by staabm** [comment]
```
if ('REX_VALUE[4]' != '') {
    $href = 'REX_VALUE[4]';
}
```

diese code sollte nicht zu errors führen.

@dergel unter welchem pfad liegt bei euch das developer addon?

diese errors werden anhand eines pfad patterns ignoriert... ggf. passt das pattern nicht auf das yakamara path layout?

https://github.com/FriendsOfREDAXO/rexstan/blob/84f3e4415d4e705c741ac4c8551d796254bb7ae8/default-config.neon#L18-L30
