### ISSUE TITLE
Modulüberprüfung verbessern - Wenn die Eingabe nicht existiert, in der Ausgabe als Fehler anzeigen.

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/rexstan#205]
z.B. wenn im output.php ein REX_VALUE[1] / REX_VALUE[id=15] oder ähnliches ist, was in der Eingabe gar nicht erst vorhanden ist wäre eine Fehrlermeldung fantastisch :)

**Comment by staabm** [comment]
Wird nicht implementiert da redaxo sich von rex vars entfernen wird
