### ISSUE TITLE
Logo erstellen - Mischung aus FOR und PHPStan

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/rexstan#211]
Quasi der REX mit einer Lupe oder so .. 

https://phpstan.org/logo.3f4f2820.png

https://raw.githubusercontent.com/FriendsOfREDAXO/friendsofredaxo.github.io/assets/v2/FOR-badge-dark-rgb.png

**Comment by dergel** [comment]
@subunity

**Comment by subunity** [comment]
TAKE A LOOK...

![REX-STAN-2](https://user-images.githubusercontent.com/4094576/201651135-85309408-c6b7-40e5-b1e9-4351cea84641.jpg)

**Comment by staabm** [comment]
Oh geil - gefällt mir sehr gut. Gibts das als SVG? :-)

**Comment by subunity** [comment]
![REX STAN negativ bg](https://user-images.githubusercontent.com/4094576/202147045-12a72ddf-bc3c-4c32-bde9-54ebd6ad79ad.svg)
![REX STAN negativ](https://user-images.githubusercontent.com/4094576/202147050-b3d16737-8459-456d-b8f6-fdb134d92cad.svg)
![REX STAN negativ bg](https://user-images.githubusercontent.com/4094576/202147053-496df44c-7532-4172-8483-c746382e5909.png)
![REX STAN negativ](https://user-images.githubusercontent.com/4094576/202147064-dcd561df-0852-4558-aa62-5eb52acc9100.png)
![REX STAN Positiv](https://user-images.githubusercontent.com/4094576/202147072-3e121dca-bddc-4cdb-930c-89aac0bf1887.png)
![REX STAN positiv](https://user-images.githubusercontent.com/4094576/202147073-adbc1b0b-0595-4f10-bdc3-f5e4492b8001.svg)
