### ISSUE TITLE
In einzelnen Dateien offentlichliche falsche Meldungen

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#216]
Fortsetzung aus Slack: Das ist möglicherweise kein RexStan oder PhpStan-Problem, sondern liegt an meiner Installation. Sicher bin ich mir nicht und melde das Issue daher doch. Gerne zu machen, wenn es so ist.

**Description / Beschreibung**

Seltsame Effekte beim Scan meines **Project**-Addons. Es gibt Dateien, in denen Fehler gemeldet werden, die nachweislich nicht existieren. Das sind Trivialitäten und keine seltenen Ausnähme-Situationen. Meist wird eine fehlende Rückgabe gemeldet, wie in diesem Beispiel:
```
Method rex_yform_value_tabs::getDescription() should return string but return statement is missing.
```
Aber: da fehlt offensichtlich nix!
```php
public function getDescription(): string
{
    return 'tabs|name|label|aktiv[1,2]|[tabgroup]';
}
```
Das ist kein Einzelfall. Wenn ich gezielt die Datei analysiere (nur die eine Datei) verschwindet die Meldung. Cache-Löschen bewirkt nichts. Kleinere Änderungen in der Datei (Leerzeile in Kommentaren z.B.) hilft manchmal. Keine der Lösungen ist nachhaltig. 

Zur Zeit werden hartnäckg zwei Dateien angemeckert, jeder der Fehler ist nicht richtig.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/10065904/200181981-23f5ca9a-4a6d-411f-92ab-8576ce5c4698.png">

Zwischenzeitlich habe ich den Verdacht, es könnte an meiner Installation liegen. Das Addon liegt an zentraler Stelle meines lokalen Rechners. Von dort ist es per SymLink in die Redaxo-Instanzen eingebunden. Löse ich das auf, packe also eine Kopie des Verzeichnisses als physisches Verzeichnis an die Stelle des Links, sind die falschen Fehler weg.

Es spricht also einiges dafür, dass die SymLink-Konstruktion mit RexStan oder PhpStan kollidiert. Möglicher weise bei eine Pfad-Normierung mit `realpath()`? Damit hatte ich nämlich auch schon Trouble.

Falls gewünscht kann ich das Project-Addon via GitHub zur Verfügung stellen.

Die Tests liefen mit unterschiedlichen RexStan-Konfiguration (PHP 8.1-8.2, mit und ohne Extensions, verschiedene Level). Die Anzahl Meldungen ändert sich, aber nicht der Effekt an sich. 

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.1
PHP: 8.0, 8.1, 8.2
AddOns: RexStan 1.0.57

**Comment by staabm** [comment]
Ein repo was man auschecken kann und man den fehler "sofort" sieht wäre super. 

D.h. Ggf ein volles redaxo demo repo o.ä.

**Comment by christophboecker** [comment]
Ich kann mal schauen, ob ich was zusammengebaut bekomme. Ich würde versuchen, ein nacktes REDAXO aufzusetzen und nur mit meinem Project-Addon und den dafür unvermeidbaren Abhängigkeiten (äh YForm, Adminer, Rexstan) zu versehen. Das könnte ich dann nach Github hochladen.

Wie macht man es dann mit 

Wie müsste ich mit der Datenbank verfahren? Export ohne Tabelle rex_user mit in das Root? Aus der rex_config auch alles raus, was verfänglich wäre.

Und in der config.yml den DB-Zugang löschen.

Fragt sich noch, wie man die Sache mit dem Symlink unterbringt?

**Comment by staabm** [comment]
vllt ist es auch einfacher reproduzierbar wenn du ein kleines phpstan setup machst und dort mit nem symlink arbeitest

**Comment by staabm** [comment]
Symlinks sind ein bekanntes problem mit phpstan.
