### ISSUE TITLE
Platzhalter in Modulen führt zu Fehler

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/rexstan#222]
Der Code
```
$cols = "REX_VALUE[20]";
	if($cols == "") {
```
führt zum Fehler "If condition is always false."

**Comment by staabm** [comment]
unit test in https://github.com/FriendsOfREDAXO/rexstan/pull/208 eingebaut. scheint mit dem PR behoben zu werden.

bis das in rexstan enthalten ist, brauch ich allerdings erst noch ein redaxo release

**Comment by TobiasKrais** [comment]
Danke Markus! Dann schließe ich den Issue wieder.

**Comment by staabm** [comment]
(war dennoch hilfreich, bitte gerne neue aufmachen wenn bedarf besteht)
