### ISSUE TITLE
Call to undefined function rexstan\proc_open() nach update von 1.0.5.6

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/rexstan#228]
Folgenden Fehler bekomme ich beim Update von 1.0.51 auf 1.0.59
Update bis 1.0.56 läuft noch, danach ist schluss.

**Error:** Call to undefined function rexstan\proc_open()
**File:** redaxo/src/addons/.new.rexstan/lib/RexStan.php
**Line:** 164

<details>
<summary>Stacktrace</summary>

| Function                                | File                                                       | Line     |
| --------------------------------------- | ---------------------------------------------------------- | -------- |
| rexstan\RexStan::execCmd                | redaxo/src/addons/.new.rexstan/install.php                 | 14       |
| require                                 | redaxo/src/core/lib/packages/package.php                   | 284      |
| rex_package->includeFile                | redaxo/src/addons/.new.rexstan/update.php                  | 5        |
| require                                 | redaxo/src/core/lib/packages/package.php                   | 280      |
| rex_package->includeFile                | redaxo/src/addons/install/lib/package/package_update.php   | 63       |
| rex_install_package_update->doAction    | redaxo/src/addons/install/lib/package/package_download.php | 44       |
| rex_install_package_download->run       | redaxo/src/addons/install/lib/api/api_package_update.php   | 21       |
| rex_api_install_package_update->execute | redaxo/src/core/lib/api_function.php                       | 179      |
| rex_api_function::handleCall            | redaxo/src/core/backend.php                                | 235      |
| require                                 | redaxo/src/core/boot.php                                   | 143      |
| require                                 | redaxo/index.php                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.14.1, PHP 8.0.25, MariaDB 10.3.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.25     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.34 |
| Character set | utf8            |

| Database 2    |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.34 |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/107.0 |
|      Protocol | HTTP/2.0      |
|         HTTPS | yes           |

| Packages                   |            |
| -------------------------: | :--------- |
|                    adminer | 1.9.2      |
|                     backup | 2.8.2      |
|                be_password | 2.0.1      |
|                   be_style | 3.1.0      |
|            be_style/redaxo | 3.1.0      |
|                    bloecks | 3.1.1      |
|           bloecks/cutncopy | 3.1.1      |
|             bloecks/status | 3.1.1      |
|               cache_warmup | 4.0.0      |
|                       cke5 | 5.2.0      |
|                    cronjob | 2.9.0      |
|                      debug | 1.2.2      |
|                  developer | 3.9.1      |
|                 focuspoint | 4.0.2      |
|            global_settings | 2.8.2      |
|                    install | 2.10.0     |
|                maintenance | 2.8.5      |
|                     mblock | 3.4.7      |
|              media_manager | 2.13.0     |
|               media_srcset | 2.1.0      |
|                  mediapool | 2.12.0     |
|                   metainfo | 2.9.0      |
|                      mform | 7.2.2      |
|                 mform/docs | 1.1        |
|              minify_images | 2.2.0      |
|                  phpmailer | 2.11.2     |
|                    project | dev        |
|            project_manager | 1.4.0      |
|     project_manager/client | 1.1.0      |
|           quick_navigation | 6.0.0      |
|                     rexpdf | 1.1.0      |
|                    rexstan | 1.0.51     |
|                      sprog | 1.4.0      |
|                  structure | 2.14.1     |
|          structure/content | 2.14.1     |
|           structure_tweaks | 1.4.0      |
|                      theme | 1.3.3      |
|                   ui_tools | 1.2.2      |
|                      users | 2.9.0      |
|                voucher_app | dev        |
|                      yform | 4.0.4      |
|                yform/email | 4.0.4      |
|              yform/manager | 4.0.4      |
|      yform_spam_protection | 1.2.1      |
| yform_standalone_validator | 1.0.2      |
|                   yrewrite | 2.9.1      |
</details>

**Comment by staabm** [comment]
@marcohanke danke. gerne den fix aus https://github.com/FriendsOfREDAXO/rexstan/commit/41b9a8ae5c9413278743616539fae958a7b7b503 mal lokal testen

**Comment by marcohanke** [comment]
Hey @staabm hiflt auch nicht.
Liegt aber daran, dass proc_open() am Server nicht existiert.
Könnte man die Voraussetzung abfangen und die Meldung entsprechend anpassen ???

**Comment by staabm** [comment]
hab jetzt eine explizite fehlermeldung eingebaut, bitte nochmal prüfen

**Comment by marcohanke** [comment]
Gestet, läuft. Danke
