### ISSUE TITLE
durch sea level rules kommt man nicht mehr auf 0 errors

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#229]
**Description / Beschreibung**

die sea level rules werden zwar nicht angezeigt, da deren errors aber im hintergrund existieren kann man aktuell nicht mehr auf 0 probleme kommen

![grafik](https://user-images.githubusercontent.com/120441/202241823-4f999dc1-52fb-4613-9bc9-aeca52906f9e.png)

![grafik](https://user-images.githubusercontent.com/120441/202241774-a622edde-afeb-42f0-b050-491666b792bd.png)

gemeldet von Andreas im Slack

**Comment by aeberhard** [comment]
Passt!
