### ISSUE TITLE
searchit liefert selbst in level 9 keine fehler

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#23]
gemeldet von Norbert.. muss man mal schauen was da los ist..

**Comment by skerbis** [comment]
Bei mir Level 3 in der WebUi
<img width="1075" alt="Bildschirmfoto 2022-06-14 um 14 23 12" src="https://user-images.githubusercontent.com/791247/173576170-e9a62b90-0817-4a24-a206-afac3354e873.png">

**Comment by tyrant88** [comment]
dann bin ich ja beruhigt.

**Comment by staabm** [comment]
bei mir funktioniert es auch. @tyrant88 wenn es bei dir reproduzierbar ist, können wir evtl. mal zusammen mit screen-sharing drauf schauen

**Comment by tyrant88** [comment]
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/173673878-35d049fb-4748-49c5-be6a-293ca72f0418.jpg)
Danke, habe es gefunden. War einfach nicht genug Speicher in php CLI da für die Masse an Fehlern :-)

**Comment by staabm** [comment]
danke für den hinweis. hab ich im FAQ ergänzt https://github.com/FriendsOfREDAXO/rexstan/commit/fbb4e60bf38e64e3689848a5fd6e2b17b647904d

**Comment by tyrant88** [comment]
Cool, gern. 
Willst du nicht gleich dazu schreiben, dass der Speicher für das CLI-PHP erhöht werden muss? Das spart vielleicht mancheinem einen Arbeitsschritt.
