### ISSUE TITLE
Extension PHPUnit funktioniert nicht auf Windows

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexstan#231]
![image](https://user-images.githubusercontent.com/330560/202318574-41c8a035-a420-4b16-b2a2-38344c96bca3.png)

Bin mir nicht sicher ob die Extension nicht schon mal funktioniert hatte.

**Comment by staabm** [comment]
nach dem update von rexstan aus dem installer, einmal in die einstellungen gehen und neu abspeichern - sollte das problem lösen.

**Comment by aeberhard** [comment]
Super! passt jetzt wieder!
