### ISSUE TITLE
Zusammenfassung Whoopst auf Windows

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexstan#232]
Die Funktion ging aber definitiv schon mal.

Ich meine auch dass hier bei den Zahlen das Problem mit den sea leveln besteht. 
Level 9 war ohne Fehler und bei Zusammenfassung standen 3 Fehler. 
https://github.com/FriendsOfREDAXO/rexstan/issues/229 

**Exception:** Unable to graph baseline: Der Befehl "5df9506909095eda272b5af454d2fc27" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**File:** redaxo\src\addons\rexstan\lib\RexStan.php
**Line:** 113

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                        | Line     |
| -------------------------------------------- | ------------------------------------------- | -------- |
| rexstan\RexStan::analyzeBaseline             | redaxo\src\addons\rexstan\pages\summary.php | 6        |
| require                                      | redaxo\src\core\lib\packages\package.php    | 285      |
| rex_package->includeFile                     | redaxo\src\core\lib\be\controller.php       | 485      |
| rex_be_controller::{closure}                 | redaxo\src\core\lib\util\timer.php          | 57       |
| rex_timer::measure                           | redaxo\src\core\lib\be\controller.php       | 486      |
| rex_be_controller::includePath               | redaxo\src\core\lib\be\controller.php       | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo\src\addons\rexstan\pages\index.php   | 7        |
| require                                      | redaxo\src\core\lib\packages\package.php    | 285      |
| rex_package->includeFile                     | redaxo\src\core\lib\be\controller.php       | 485      |
| rex_be_controller::{closure}                 | redaxo\src\core\lib\util\timer.php          | 57       |
| rex_timer::measure                           | redaxo\src\core\lib\be\controller.php       | 486      |
| rex_be_controller::includePath               | redaxo\src\core\lib\be\controller.php       | 415      |
| rex_be_controller::includeCurrentPage        | redaxo\src\core\backend.php                 | 238      |
| require                                      | redaxo\src\core\boot.php                    | 143      |
| require                                      | redaxo\index.php                            | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.2, PHP 7.4.10, MariaDB 10.4.14)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.4.10                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.14 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.46  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/107.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | no               |

| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.9.2       |
|                      backup | 2.8.0       |
|                    be_style | 3.0.1       |
|         be_style/customizer | 3.0.1       |
|             be_style/redaxo | 3.0.1       |
|             consent_manager | 3.0.4       |
|                 insert_text | 2.0.1       |
|                     install | 2.9.3       |
|               media_manager | 2.12.1      |
|                   mediapool | 2.11.2      |
|                    metainfo | 2.8.4       |
|                     project | dev         |
|                  rex_gitapi | 1.0.0beta1  |
|                     rexstan | 1.0.61      |
|                   structure | 2.13.2      |
|           structure/content | 2.13.2      |
|                       users | 2.8.2       |
|               xoutputfilter | 3.0.0-beta1 |
|        xoutputfilter/abbrev | 3.0.0       |
|       xoutputfilter/backend | 3.0.0       |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
| xoutputfilter/import_export | 3.0.0       |
|     xoutputfilter/languages | 3.0.0       |

</details>

**Comment by staabm** [comment]
danke für den report.

kannst du hier mal ein bissl ausprobieren, ob du eine variante hinbekommst, die das command auch unter windows funktionieren lässt?

https://github.com/FriendsOfREDAXO/rexstan/blob/cfebd7299bf754801b257f6800ea25ff442bddfe/lib/RexStan.php#L111

**Comment by aeberhard** [comment]
Hi Markus,
gerne teste ich mit Windows wenn Du mich in die richtige Richtung schubst :)

https://github.com/FriendsOfREDAXO/rexstan/blob/cfebd7299bf754801b257f6800ea25ff442bddfe/lib/RexStan.php#L86

`$configSignature` enthält eine Pipe, das ist unter Windows nicht zulässig für Datei/Verzeichnisnamen.
![image](https://user-images.githubusercontent.com/330560/205374215-1c1e2ac8-f939-4f6e-864b-11ced0c86c4d.png)

Die beiden folgenden Zeilen liefern daher ungültige Verzeichnis-Pfade

https://github.com/FriendsOfREDAXO/rexstan/blob/cfebd7299bf754801b257f6800ea25ff442bddfe/lib/RexStan.php#L93-L94

![image](https://user-images.githubusercontent.com/330560/205374571-302dee56-5ae5-4905-9303-4cd672f87d63.png)

**Lösung:** 
Wenn ich die Pipe in `$configSignature` mit str_replace entferne funktioniert es.
Trotz noch "fehlerhaften" Slashes in den Pfaden.

**Comment by aeberhard** [comment]
Ah da ist der Schuldige
https://github.com/FriendsOfREDAXO/rexstan/blob/a2f4b1d65fcf62dff25ff4eea4ea12524c113c7e/lib/RexStanUserConfig.php#L74

**Comment by aeberhard** [comment]
Hier einfach durch Strindebich ersetzen und läuft.

**Comment by staabm** [comment]
Danke für die Analyse. Falls du einen PR beisteuern willst, gerne.

ansosnten fix ich es später.

**Comment by aeberhard** [comment]
Habe 2 PR's reingestellt direkt hier Online.
Der zweite sorgt für korrekte Pfade unter Windows. Lokal natürlich getestet :)
