### ISSUE TITLE
Fehlermeldung in PHPStorm "Resolver.php" bei Versionen > 1.0.55

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/rexstan#233]
**Description / Beschreibung**

Wenn ich rextstan auf eine Version > 1.0.55 update erhalte ich folgende Fehlermeldung:

```
phpstan: ! [NOTE] The Xdebug PHP extension is active, but "--xdebug" is not used. 
This ! may slow down performance and the process will not halt at ! breakpoints.   

In Resolver.php line 452:  Service of type PHPStan\Rules\PHPUnit\ClassCoversExistsRule: 
Service of typ e PHPStan\Rules\PHPUnit\CoversHelper required by $coversHelper in ClassCove rsExistsRule::__construct() not found. Did you add it to configuration file ?   
analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [-b|--generate-baseline [GENERATE-BASELINE]] [--allow-empty-baseline] [--memory-limit MEMORY-LIMIT] [--xdebug] [--fix] [--watch] [--pro] [--] [<paths>...]
```

Entferne ich die PHPUnit Extension in den Einstellungen scheint es zu funktionieren.

Fehlt da evtl. etwas bei mir im System? Habe ich evtl. etwas falsch konfiguriert?

**Comment by staabm** [comment]
dakne für die meldung. verwendest du auch windows?

hier wurde was ähnliches gemeldet https://github.com/FriendsOfREDAXO/rexstan/issues/231

**Comment by staabm** [comment]
nach dem update von rexstan aus dem installer, einmal in die einstellungen gehen und neu abspeichern - sollte das problem lösen.

**Comment by anveno** [comment]
Ja. Mit der 1.0.62 scheint es zu funktionieren.
