### ISSUE TITLE
rexstan Präfix `rex` entfernen, solange das Projekt noch am Anfang steht 

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/rexstan#24]
Als Anregung: Allgemein herrschte mal darüber Konsens, REDAXO-Addons ohne `rex` am Anfang zu betiteln. Da es ein FOR-Addon ist, fände ich es gut, wenn FOR sich daran weiter hält.

**Comment by staabm** [comment]
so gesehen ist es nach längerem drüber nachdenken kein "rex" prefix, sondern der name des addons ist "rexstan".
