### ISSUE TITLE
Kann AddOn nicht installieren: sh: php: command not found

### ISSUE THREAD

**Issue by xong** [FriendsOfREDAXO/rexstan#250]
**Description / Beschreibung**

Fehlermeldung bei Installation des AddOns:
```
AddOn rexstan konnte aus folgendem Grund nicht installiert werden:
Unable to determine PHP CLI version. Make sure PHP is installed in the CLI and availabe within your system PATH.
```

**Affected versions / Verwendete Versionen**

Jungfräuliche Redaxo-Installation mit ein paar zusätzlichen AddOns unter MacOS Ventura 13.0.1:
<details>
<summary>System report (REDAXO 5.14.1, PHP 8.1.11, MariaDB 10.8.3)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.11     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 10.8.3 |
| Character set | utf8mb4        |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.54  |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/107.0 |
|      Protocol | HTTP/1.1      |
|         HTTPS | yes           |

| Packages          |            |
| ----------------: | :--------- |
|           adminer | 1.9.2      |
|            backup | 2.8.2      |
|          be_style | 3.1.0      |
|   be_style/redaxo | 3.1.0      |
|           bloecks | 3.1.1      |
|  bloecks/cutncopy | 3.1.1      |
| bloecks/dragndrop | 3.1.1      |
|    bloecks/status | 3.1.1      |
|         developer | 3.9.1      |
|        focuspoint | 4.0.2      |
|           install | 2.10.0     |
|            mblock | 3.4.7      |
|     media_manager | 2.13.0     |
|         mediapool | 2.12.0     |
|          metainfo | 2.9.0      |
|         phpmailer | 2.11.2     |
|           project | dev        |
|  quick_navigation | 6.0.1      |
|          redactor | 2.3.0      |
|         structure | 2.14.1     |
| structure/content | 2.14.1     |
|             users | 2.9.0      |
|             yakme | 0.0.2      |
|           ydeploy | 1.1.1      |
|             yform | 4.0.4      |
|       yform/email | 4.0.4      |
|     yform/manager | 4.0.4      |

</details>

**Did it whoops? / Whoops erhalten?**

Kein Whoops, aber die Fehlermeldung von [install.php](https://github.com/FriendsOfREDAXO/rexstan/blob/main/install.php#L14) gibt `sh: php: command not found
` zurück.
Verwende ich den Befehl `php  -r "echo PHP_VERSION_ID;"` direkt im Terminal bekomme ich aber `80111%` zurück.

Setze ich den [Pfad von PHP](https://github.com/FriendsOfREDAXO/rexstan/blob/main/lib/RexStan.php#L33) auf `/usr/local/bin/php` funktioniert zwar die Installation, allerdings gibt es dann weitere Fehler auf den Unterseiten des AddOns.

**Comment by aeberhard** [comment]
@xong Du musst PHP im SystemPfad drin haben. Unter windows gibt es da eine PATH-Variable die man setzen kann.
Muss es auf dem Mac auch irgendwie geben.

**Comment by staabm** [comment]
@xong d.h. es kommt keine der beiden meldungen hier?

https://github.com/FriendsOfREDAXO/rexstan/blob/0f712d526551754b663fa07553cfe81048597603/install.php#L23

https://github.com/FriendsOfREDAXO/rexstan/blob/0f712d526551754b663fa07553cfe81048597603/install.php#L27

**Comment by xong** [comment]
> @xong d.h. es kommt keine der beiden meldungen hier?

Zeile 27 schlägt an. Muss ich PHP noch irgendwie besonders installieren? Wie geschrieben, in der Konsole kann ich `php` aufrufen.

**Comment by aeberhard** [comment]
@xong wie gesagt du musst die environment-Variable setzen
https://phoenixnap.com/kb/set-environment-variable-mac sieht ja fast aus wie unter Windows :)

In der Console ist die wohl gesetzt aber in deiner MAMP-Umgebung evtl. nicht.

**Comment by staabm** [comment]
@xong unter welchem pfad ist dein php installiert?

**Comment by xong** [comment]
Ich hab PHP, Apache und MariaDB nach dieser Anleitung installiert: https://getgrav.org/blog/macos-monterey-apache-multiple-php-versions
Läuft also grundsätzlich mit Homebrew.

`echo $PATH` gibt `/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin` aus. PHP liegt unter `/usr/local/bin/php`.
Sieht für mich eigentlich richtig konfiguriert aus.

**Comment by aeberhard** [comment]
Pack mal /usr/local/bin/php noch beim $PATH dazu!

**Comment by staabm** [comment]
andreas meint vermutlich hier: https://github.com/FriendsOfREDAXO/rexstan/blob/0f712d526551754b663fa07553cfe81048597603/lib/RexStan.php#L30

**Comment by aeberhard** [comment]
Die Systemenvironment-Variable $PATH sollte gesetzt werden wie ich oben bereits geschroben habe
https://phoenixnap.com/kb/set-environment-variable-mac

Das macht denke ich auch die Zeile 30 aus RexStan.php wenn sie denn ausgeführt wird.

Dein PHP-Pfad entspricht wahrscheinlich nicht dem MAMP-Pfad

**Comment by staabm** [comment]
ich verwende auch das getgrav setup und bei mir gehts. daher bin ich ein bissl verwirrt warum es bei robert nicht geht

**Comment by xong** [comment]
Ich vermute, es liegt an meinem lokalen Server:
```
$output = \rexstan\RexStan::execCmd('echo $PATH', $stderrOutput, $exitCode);
echo $output;
```
Bekomme: `/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by staabm** [comment]
@xong kommt der auf deinem rechner hier vorbei?

https://github.com/FriendsOfREDAXO/rexstan/blob/0f712d526551754b663fa07553cfe81048597603/lib/RexStan.php 

d.h. reicht es wenn wir dort deinen pfad aufnehmen?

**Comment by xong** [comment]
Ne, `is_executable` in Zeile 29 schlägt fehl.

**Comment by aeberhard** [comment]
Da ist ja auch noch nicht dein Pfad drin :)
mach doch mal in Zeile 28
`$mampPhp = "/usr/local/bin/php";`

**Comment by xong** [comment]
Prinzipiell ja, aber in [Zeile 37](https://github.com/FriendsOfREDAXO/rexstan/blob/0f3a02c1ce232d8bf0d0f43b70bf71d420e97e08/lib/RexStan.php#L37) wird $path nicht ersetzt.

Und man sollte auch nicht vergessen, dass der Fehler hier in der Konfiguration meines Apaches liegt. Ich bin mir sicher, dass ich das Problem lösen könnte, wenn ich ein bisschen Aufwand betreibe.

Aber prinzipiell unterstütze ich den PR. =)
