### ISSUE TITLE
SQL-Injection setWhere()

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/rexstan#280]
**Description / Beschreibung**
Folgender code 
```
$kunde = rex_sql::factory();
$kunde->setTable('rex_frontendlogin');
$kunde->setWhere('pw_vergesskey = '.$kunde->escape($key).' and pw_date >= '.(time() - (60 * 60 * 72)).' '); //
// $kunde->setDebug(true);
$kunde->select();
```
generiert folgenden Fehler: 
`
Possible SQL-injection in expression $kunde->escape($key).
💡 Consider use of more SQL-safe types, prepared statements, rex_sql::escape(), rex_sql::escapeIdentifier() or rex_sql::in().
`

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1.13 
Database:
Browser: 
AddOns:
rexstan | 1.0.68

**Did it whoops? / Whoops erhalten?**

**Comment by staabm** [comment]
ich kann den fehler nicht reproduzieren.

ist er für dich noch immer reproduzierbar?

**Comment by thorol** [comment]
Ja, bei mir kommt es reproduzierbar:
`$key` ist ein Parameter einer Methode: 

```
  /**
     * changePassword.
     *
     * @param  string $key
     * @param  string $loginpw
     * @param  string $loginpw1
     * @return array<string>
     */
    public static function changePassword($key, $loginpw, $loginpw1)
    {
        $kunde = rex_sql::factory();
        $kunde->setTable('rex_frontendlogin');
        $kunde->setWhere('pw_vergesskey = '.$kunde->escape($key).' and pw_date >= '.(time() - (60 * 60 * 72)).' '); //
        // $kunde->setDebug(true);
        $kunde->select();
        .......
      }
```

**Comment by thorol** [comment]
Habe es an anderer Stelle ähnlich gemacht und gleiche Meldung:
![image](https://user-images.githubusercontent.com/25980352/209869576-9bfd16f6-5fe3-4cb7-bad8-81b1c053bdac.png)

**Comment by staabm** [comment]
Kann ich einen zugang zum system bekommen?

**Comment by thorol** [comment]
Ist auf einem localhost. Kann ich dir mit sonstigen Informationen weiterhelfen?

**Comment by staabm** [comment]
Kannst du ein kleines repository erzeugen wo das problem einfach reproduzierbar ist?

**Comment by thorol** [comment]
Ja das mache ich, ich melde mich, wenn ich soweit bin.

**Comment by thorol** [comment]
Ging schneller als gedacht: https://github.com/thorol/rexstansqltest

**Comment by thorol** [comment]
![image](https://user-images.githubusercontent.com/25980352/209871984-ae0b00bd-b50e-4b05-89e1-a9490e610d25.png)
![image](https://user-images.githubusercontent.com/25980352/209872010-95886c83-c438-4089-9cb9-9eb54437a019.png)

**Comment by staabm** [comment]
hmm komisch..

<img width="847" alt="grafik" src="https://user-images.githubusercontent.com/120441/209872926-eb1bcbd5-608f-4694-88ae-3142807ff420.png">

**Comment by thorol** [comment]
An was kann es dann noch liegen? Der Cache kann es eigentlich nicht sein, da es ein neues Addon war.

**Comment by staabm** [comment]
kannst du bei dir lokal mal versuchen zu debuggen welchen return-weg er in `RexSqlInjectionRule->findInsecureSqlExpr()` nimmt um letztendlich ein non-null return zu erzeugen?

falls du einen debugger hast, könntest du dort schritt für schritt durchlaufen

**Comment by staabm** [comment]
eine weitere idee: du könntest in `PhpDocUtil` mal `var_dump($phpDocString); einfügen und auch schauen ob der regex etwas trifft: `preg_match('/@psalm-taint-escape\s+(\S+).*$/m', $phpDocString, $matches)`

es könnte ggf. sein dass der regex nicht funktioniert (z.b. windows vs. linux o.ä.)

**Comment by staabm** [comment]
ich habe eine vermutung: da du 5.14.2 verwendest fehlt im phpdoc von `rex_sql->escape()` der phpdoc

5.14.2
https://github.com/redaxo/redaxo/blob/e733fd2790898521dfd47e850aff11779c29bd61/redaxo/src/core/lib/sql/sql.php#L1398-L1406

5.15 (aktuell noch redaxo git version)
https://github.com/redaxo/redaxo/blob/b9458fb2970ec04353a690dfe7f51f37b224ef9d/redaxo/src/core/lib/sql/sql.php#L1438

**Comment by thorol** [comment]
Debugger habe ich leider keinen, ich sollte mir mal anschauen, wie man in VSC debuggt. 

Ich habe die sql.php von 5.15 genommen und meine überschrieben, leider keine Änderung.

**Comment by thorol** [comment]
> eine weitere idee: du könntest in `PhpDocUtil` mal `var_dump($phpDocString);` einfügen und auch schauen ob der regex etwas trifft: `preg_match('/@psalm-taint-escape\s+(\S+).*$/m', $phpDocString, $matches)`
> 
> es könnte ggf. sein dass der regex nicht funktioniert (z.b. windows vs. linux o.ä.)

Wo sollten die var_dump zu sehen sein? Direkt im Analyse-Fenster?

**Comment by thorol** [comment]
![image](https://user-images.githubusercontent.com/25980352/209875805-fd229ee8-d0f9-4764-88a8-f213b3eea9b6.png)
Sollte er dann nicht die Ausführung unterbrechen?

**Comment by staabm** [comment]
> Ich habe die sql.php von 5.15 genommen und meine überschrieben, leider keine Änderung.

ggf musst du `vendor/bin/phpstan clear-result-cache` im rexstan verzeichnis ausführen, nach dieser Änderung

**Comment by thorol** [comment]
ok, nun geht es:
![image](https://user-images.githubusercontent.com/25980352/209876919-1db88a63-5da5-4286-86c5-3caf43d184e9.png)

Danke fürs Schauen!

**Comment by staabm** [comment]
ok danke. quint essenz: mit redaxo 5.15 wirds dann gehen
