### ISSUE TITLE
Extension Points 

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/rexstan#282]
**Description / Beschreibung**
Folgender Code:
```
$name = null;
$name = rex_extension::registerPoint(new rex_extension_point(
	'NEW_NAME',
	$name,
	[
		'id' => $id,
		'output' => $output,
	]
));
if (null !== $name) {
	return $name;
}
```
erzeugte folgenden Fehler:
`
Strict comparison using !== between null and null will always evaluate to false.
`
`$name` kann jedoch über den extension point geändert werden 

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1.13
Database:
Browser:
AddOns:
rexstan | 1.0.68

**Did it whoops? / Whoops erhalten?**

**Comment by staabm** [comment]
fix kommt im nächsten redaxo core release: https://github.com/redaxo/redaxo/pull/5455
