### ISSUE TITLE
Faq: Generic am beispiel EP erklären

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#30]
> parameter $ep with generic class rex_extension_point but does not specify its types: T

**Comment by staabm** [comment]
@christophboecker bitte lies mal drüber ob die beschreibung in https://github.com/FriendsOfREDAXO/rexstan/commit/abe28d1fad11f795106cc641d11efded3000c62c für dich hilfreich ist

**Comment by christophboecker** [comment]
Ja, das passt, die beiden EP-bezogenen Meldungen konnte ich damit auflösen. Notfalls geht es auch mit der "Fliegenpatche" `mixed`. Was es nicht alles gibt. Danke.
