### ISSUE TITLE
rex_clang::get mit ID 1 bzw. rex_clang::getStartId()

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/rexstan#301]
**Description / Beschreibung**
Ich habe eine Methode, die als Parameter den Typ rex_clang erwartet. 
```$object->methode(rex_clang::get(rex_clang::getStartId()));```

Rexstan gibt folgenden Hinweis:
```Parameter #1 $clang of method class::setClang() expects rex_clang, rex_clang|null given.```

Die letzte Sprache im Backend kann eigentlich nicht gelöscht werden. Kann der Fehler abgefangen werden? 

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1.13 
Database:
Browser: 
AddOns: rexstan 1.0.75

**Did it whoops? / Whoops erhalten?**

**Comment by staabm** [comment]
in deiner beispiel-codezeile ist gar keine methode `setClang` die in der fehlermeldung benannt wird.

wäre gut die konkrete code zeile zu sehen um eine gute Antwort geben zu können.
ggf. ist das ja sogar code eines addons der ohnehin hier auf github irgendwo liegt?

falls nein wäre ein bissl mehr context (reproduzierbares code-beispiel)

**Comment by thorol** [comment]
ah sorry, dachte es wäre nicht interessant, da `rex_clang::get(rex_clang::getStartId())` niemals null liefern wird.
Die Methode verlangt rex_clang und nicht rex_clang|null

Die konkrete Zeile lautet, leider nicht auf Github:
`$pro->setClang(rex_clang::get(rex_clang::getStartId()));`

Die Methode ist ein Setter:
```    /**
     * setClang.
     *
     * @param  rex_clang $clang
     * @return void
     */
    public function setClang($clang)
    {
        $this->clang = $clang;
    }
```

**Comment by staabm** [comment]
@gharlan da es kein system ohne clang gibt und `rex_clang::getStartId()` die offline clangs ignoriert, müsste die methode aktuell immer 1 zurück geben oder?

**Comment by gharlan** [comment]
`rex_clang::get(rex_clang::getStartId())` müsste in der Tat immer eine clang liefern.
`rex_clang::get` ist aber halt ansonsten schon nullable. Wenn eben eine nicht existente ID übergeben wird.

**Comment by staabm** [comment]
@thorol soeben im installer ist ein update mit dem fix gelandet. bitte gegenprüfen
