### ISSUE TITLE
use separate result cache per redaxo instance

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#328]
**Feature description / Feature Beschreibung**

when having several redaxo installations on the same machine the result-cache should not be overridden across projects, so switching between projects does not need a full initial scan

**Comment by christophboecker** [comment]
Für mich Dummie zum Verständnis: was wird denn durch diesen Cache erwischt? Sind das daten, die komplett unabhängig sind vond er konkreten Readxo-Instanz? Denn jede Instanz hat ja so ihren eigenen Satz an Addons und damit Klassen ..

**Comment by staabm** [comment]
der cache enthält daten zu den dateien die analysiert werden und wie diese zusammehängen.

**Comment by christophboecker** [comment]
Hm. Was auf meiner Platte in Instanz A liegt ist nur begrenzt deckungsgleich mit Instanz B. Wieso hilft ein Cache für Instanz A bei der Analyse von Instanz B. Die beiden können sich ganz erheblich unterscheiden.

**Comment by christophboecker** [comment]
> ... switching between projects does not need a full initial scan

> ... somit beim wechsel zwischen projekten wird immer der cache überschrieben

Die beiden Sätze kriege ich jetzt nicht mehr passend übereinander gelegt. Wenn der Cache  immer überschrieben wird beim Wechsel in eine andere Instanz, findet doch ein komplett neuer Scan statt. Dann wäre es doch besser, der Cache liegt je Instanz im Instanz-Verzeichnis.  

Ist mir am Ende nicht so wichtig; solange Rechner und Platte fix genug sind, kann phpstan von mir aus immer bei null starten. Ich möchte es halt verstehen. Vieleicht lerne ich ja was daraus. :-)

**Comment by staabm** [comment]
> Dann wäre es doch besser, der Cache liegt je Instanz im Instanz-Verzeichnis.

jep, so ähnlich ist die lösung dieses issues hier. es gibt dann je instanz nen eigenen cache, daher wird er nicht mehr gegenseitig überschrieben

**Comment by christophboecker** [comment]
Dann habe ich das Issue 180° falsch verstanden. Sorry for confusing
