### ISSUE TITLE
PhpStan vermisst ab Redaxo 5.15 die Polyfills

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#345]
**Description / Beschreibung**

In einer Instanz mit der neuesten Version von Redaxo, also 5.15-beta1, wirft das RexStan/PhpStan die Meldung

<img width="888" alt="grafik" src="https://user-images.githubusercontent.com/10065904/221148967-8aacb2f2-570d-4381-84ce-7b1d1ab3e0de.png">

Vermutete Ursache: die zuvor im Vendor "symfony" zu findenden "polyfill-php80" und "polyfill-php81" entfallen ab Redaxo-Version 5.15., da 5.15 auf PHP 8.1 aufsetzt.

**Affected versions / Verwendete Versionen**

REDAXO: 5.15-beta1
PHP: 8.1.15
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

Klickt man im Menü auf "Zusammenfassung" kommt ein Whoops statt der abgefangenen Fehlermeldung:

**Request-Uri:** /lboot/kv30/redaxo/index.php?page=rexstan/summary
**Request-Method:** GET

**Exception:** Unable to generate baseline:Scanned file /Users/christoph/Sites/lboot/kv30/redaxo/src/core/vendor/symfony/polyfill-php80/bootstrap.php does not exist.

**File:** redaxo/src/addons/rexstan/lib/RexStan.php
**Line:** 123

<details>
<summary>Stacktrace</summary>

| Function | File | Line |
| -------------------------------------------- | -------------------------------------------------- | -------- |
| rexstan\RexStan::analyzeSummaryBaseline | redaxo/src/addons/rexstan/pages/summary.php | 6 |
| require | redaxo/src/core/lib/packages/package.php | 233 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 503 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 56 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 504 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 453 |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/rexstan/pages/index.php | 9 |
| require | redaxo/src/core/lib/packages/package.php | 233 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 503 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 56 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 504 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 436 |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php | 241 |
| require | redaxo/src/core/boot.php | 155 |
| require | ...../lboot/kv30/redaxo/index.php | 9 |

</details>
<details>
<summary>System report (REDAXO 5.15.0-beta1, PHP 8.1.15, MySQL 8.0.17)</summary>

| REDAXO | |
| ------------: | :----------- |
| Version | 5.15.0-beta1 |

| PHP | |
| ------------: | :----------------------------- |
| Version | 8.1.15 |
| OPcache | yes |
| Xdebug | no |
| Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database | |
| ------------: | :----------- |
| Version | MySQL 8.0.17 |
| Character set | utf8mb4 |

| Server | |
| ------------: | :------------- |
| OS | Darwin |
| SAPI | apache2handler |
| Webserver | Apache/2.4.55 |

| Request | |
| ------------: | :------------ |
| Browser | Firefox/110.0 |
| Protocol | HTTP/1.1 |
| HTTPS | no |

| Packages | |
| ------------------: | :----------- |
| adminer | 1.9.3 |
| backup | 2.9.0-beta1 |
| be_style | 3.2.0-beta1 |
| be_style/customizer | 3.2.0-beta1 |
| be_style/redaxo | 3.2.0-beta1 |
| bootsregister | 0.1 |
| cheatsheet | 0.0.1 |
| cronjob | 2.10.0-beta1 |
| developer | 3.9.2 |
| focuspoint | 4.0.3 |
| geolocation | 2.0.0-beta1 |
| install | 2.11.0-beta1 |
| markitup | 3.7.3 |
| media_manager | 2.14.0-beta1 |
| mediapool | 2.13.0-beta1 |
| metainfo | 2.10.0-beta1 |
| minibar | 2.3.1 |
| project | 0.9.0 |
| project/basis | 0.11.0 |
| project/svg | 1.0.0 |
| rexstan | 1.0.83 |
| structure | 2.15.0-beta1 |
| structure/content | 2.15.0-beta1 |
| users | 2.10.0-beta1 |
| yform | 4.0.4 |
| yform/email | 4.0.4 |
| yform/manager | 4.0.4 |
| yform_adminer | 1.0.2 |

</details>

Und für alle Fälle hier noch die RexStan-Settings:
<img width="861" alt="grafik" src="https://user-images.githubusercontent.com/10065904/221151563-6d0ce9ea-7b82-4c70-bc1b-784bd2f489a9.png">

**Comment by staabm** [comment]
versuch mal die settings neu abzuspeichern

**Comment by staabm** [comment]
hmm oder mal das addon re-installieren: ich denke rexstan verwendet bei dir gerade noch die rex 5.14 config statt der 5.15 config

siehe https://github.com/FriendsOfREDAXO/rexstan/commit/7061745551360cf1851d14217f6712a4e8e78080

**Comment by christophboecker** [comment]
Jepp, bei Neuinstallation behebt sich das Problem, leider hab ich nicht mehr im Kopf, ob ich zuerst das Update auf die neueste RexStan gemacht habe und dann den Core oder umgekehrt.

**Comment by staabm** [comment]
jop net schlimm. ich schau mal ob ich ne fehlermeldung einbauen kann mit nem hinweis wie man damit umgehen muss als user.

danke dir

**Comment by christophboecker** [comment]
Mercie!
