### ISSUE TITLE
1.0.14 Class 'mysqli' not found ?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/rexstan#35]
FOR Docker

`Error thrown in /var/www/html/redaxo/src/addons/rexstan/phpstan-bootstrap.php on line 30 while loading bootstrap file /var/www/html/redaxo/src/addons/rexstan/phpstan-bootstrap.php: Class 'mysqli' not found`

Bei älteren Versionen habe ich das nicht

<details>
<summary>System report (REDAXO 5.13.3, PHP 7.4.16, MariaDB 10.5.10)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.3     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.4.16                         |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.10 |
| Character set | utf8            |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.38  |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.4 |
|      Protocol | HTTP/1.1    |
|         HTTPS | no          |

| Packages            |            |
| ------------------: | :--------- |
|              backup | 2.8.1      |
|            be_style | 3.0.2      |
| be_style/customizer | 3.0.2      |
|     be_style/redaxo | 3.0.2      |
|      demo_community | 3.3.1      |
|           developer | 3.9.0      |
|             install | 2.9.3      |
|            markitup | 3.7.1      |
|       media_manager | 2.12.3     |
|           mediapool | 2.11.3     |
|            metainfo | 2.8.5      |
|           phpmailer | 2.10.2     |
|             project | dev        |
|             rexstan | 1.0.9      |
|           structure | 2.13.3     |
|   structure/content | 2.13.3     |
|               users | 2.8.2      |
|                ycom | 4.0.6      |
|           ycom/auth | 4.0.6      |
|          ycom/group | 4.0.6      |
|               yform | 3.4.2      |
|         yform/email | 3.4.2      |
|       yform/manager | 3.4.2      |
|            yrewrite | 2.8.3      |

</details>

**Comment by staabm** [comment]
fixed in https://github.com/FriendsOfREDAXO/rexstan/commit/7886a984bf19c595aee4d87d81859cca61324147
