### ISSUE TITLE
Tip to transactional() helper

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#359]
**Feature description / Feature Beschreibung**
Doing begin/rollback/commit transaction in all possible path can be difficult. Errors in transaction handling can lead to all sorts of strange problems. 

We should render a tip to the transactional() helper when beginTransaction() is used

**Comment by staabm** [comment]
@gharlan any opinions on this one?

**Comment by gharlan** [comment]
I agree that most of the time it is better to use the `transactional` helper. 
But I don't have strong opinion whether we should enforce this.
