### ISSUE TITLE
Klassen werden trotz addon installation nicht sofort gefunden

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#37]
Es scheint als würde noch ein caching passieren… vermutlich müsste man den phpstan cache leeren bei addon installation/de-installation etc

getestet auf 1.0.17

**Comment by staabm** [comment]
Vermutung: durch addon installation findet der redaxo autoloader mehr/andere Klassen.

Phpstan bekommt nichts davon mit dass der autoloader "schlauer" geworden ist aufgeund addOn installation und verwendet einen alten cache

**Comment by skerbis** [comment]
Hilft vielleicht ein load late?

**Comment by staabm** [comment]
ich denke nicht. redaxo kann die klassen finden, nur phpstan kann sie nicht sehen

**Comment by christophboecker** [comment]
Wo ist denn der Cache von phpstan?

**Comment by staabm** [comment]
https://phpstan.org/config-reference#caching

**Comment by staabm** [comment]
Zum löschen des caches gibts aber auch ein cli command
`phpstan clear-result-cache`
