### ISSUE TITLE
Icon zu groß direkt nach Installation

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/rexstan#370]
Ich habe rexstan frisch geladen und installiert.
Direkt nach Installation erscheint das Icon zu groß:

<img width="1058" alt="Bildschirm­foto 2023-03-05 um 17 03 46" src="https://user-images.githubusercontent.com/330436/222971796-45cf1023-eafc-44e6-a71b-d674c9647984.png">

Nach Reload passt es dann.

<details>
<summary>System report (REDAXO 5.14.3, PHP 8.2.3, MariaDB 10.11.2)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.3     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.3      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.2 |
| Character set | utf8            |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.55  |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.3 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages            |            |
| ------------------: | :--------- |
|             adminer | 1.9.3      |
|              backup | 2.8.3      |
|            be_style | 3.1.2      |
| be_style/customizer | 3.1.2      |
|     be_style/redaxo | 3.1.2      |
|             cronjob | 2.9.0      |
|               debug | 1.2.2      |
|           developer | 3.9.2      |
|       documentation | dev        |
|             install | 2.10.1     |
|            markitup | 3.7.4      |
|              mblock | 3.4.12     |
|       media_manager | 2.13.3     |
|           mediapool | 2.12.1     |
|            metainfo | 2.9.1      |
|           phpmailer | 2.11.2     |
|             project | dev        |
|    quick_navigation | 6.0.2      |
|             rexstan | 1.0.91     |
|               sprog | 1.5.1      |
|           structure | 2.14.3     |
|   structure/content | 2.14.3     |
|                 url | 1.0.1      |
|               users | 2.9.2      |
|              watson | 2.3.0      |
|             yakicon | 1.0.0      |
|                ycom | 2.1-dev    |
|           ycom/auth | 2.1-dev    |
|          ycom/group | 2.1-dev    |
|             ydeploy | 1.1.1      |
|               yform | 2.3        |
|          yform/docs | 2.3        |
|         yform/email | 2.3        |
|       yform/manager | 2.3        |
|         yform/tools | 2.3        |
|         ynewsletter | 1.0        |
|            yrewrite | 2.5        |

</details>

**Comment by christophboecker** [comment]
Kann ich bestätigen.

**Comment by staabm** [comment]
fix welcome

**Comment by gharlan** [comment]
Zur Info: Watson hat übrigens dasselbe Problem: https://github.com/tbaddade/redaxo_watson/issues/70
