### ISSUE TITLE
Klickbare Dateinamen/pfade

### ISSUE THREAD

**Issue by bloep** [FriendsOfREDAXO/rexstan#40]
Bei konfigurierter Editor-Integration sollte analog zum system log auch der Dateiname / Pfad klickbar sein (für ein einheitliches Verhalten).

![image](https://user-images.githubusercontent.com/21292755/175819436-8a2d5b32-4918-4b8b-ab57-9db7474c1b4e.png)

analog system log
![image](https://user-images.githubusercontent.com/21292755/175819486-37b44ece-0cfc-4b94-8ff3-642ca790f6c0.png)

**Comment by staabm** [comment]
Gerne. Nur die optik sollte beibehalten werden bzgl text farbe

**Comment by staabm** [comment]
die liste wurde überarbeitet. die zeilen sind noch immer nicht anklickbar, aber überall links zu haben fände ich auch zu viel.

so wie es jetzt ist, passt es erstmal für mich
