### ISSUE TITLE
vendor/ verzeichnis ist riesig

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#401]
**Feature description / Feature Beschreibung**

prüfen ob es low hanging fruits gibt

ggf. gibt es unnötige dependencies

> Die Anzahl der Dateien im Repo steigt durch installation von rexstan von 4832 auf 7677

**Comment by staabm** [comment]
upstream issue: https://github.com/paranoiq/dogma-dev/issues/1

**Comment by staabm** [comment]
upstream issue: https://github.com/phpstan/phpstan-strict-rules/pull/206

**Comment by staabm** [comment]
upstream issue: https://github.com/SQLFTW/sqlftw/issues/23

**Comment by gharlan** [comment]
Ggf. kannst du sonst auch Dateien rausfiltern, wo du weißt, dass du sie definitiv nicht brauchst?

Eventuell per composer scripts. Habe ich so zum Beispiel in sprog eingebaut für den `composer`-ordner (da der rex-autoloader sowieso den vendor-ordner in den addons scannt): https://github.com/tbaddade/redaxo_sprog/blob/master/composer.json#L9-L16

**Comment by staabm** [comment]
refs https://github.com/rectorphp/rector/issues/7842

**Comment by staabm** [comment]
ich denke mehr können wir nicht tun
