### ISSUE TITLE
YOrm: Dynamische Return-Types für getRelatedDataset, getRelatedCollection und getRelatedQuery

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/rexstan#407]
**Feature description / Feature Beschreibung**

Bei den drei Methoden getRelatedDataset, getRelatedCollection und getRelatedQuery kann leider nicht im Code der genaue Return-Type angegeben werden, da er abhängig ist von den Definitionen in der DB.
https://github.com/yakamara/redaxo_yform/blob/145a52d0b99bd10be9f206ef4ae874771993344a/plugins/manager/lib/yform/manager/dataset.php#L329-L396

Es wäre cool, wenn rexstan die Typen dynamisch ermitteln würde. Dafür müsste rexstan aber die yform-Definitionen auswerten.

```php
class Product extends rex_yform_manager_dataset
{
    public function getCategory(): Category {
        // hier meckert rexstan, weil es nicht wissen kann, dass für Feld category_id eine Relation zur category-Table gesetzt ist
        // und die table wiederum durch die Category-Model-Class repräsentiert wird
        return $this->getRelatedDataset('category_id');
    }
}
```

**Comment by staabm** [comment]
ich sehe dort auch `setRelatedCollection`, d.h. müsste dieser setter auch den type erzwingen oder kann `getRelatedCollection` nicht genauer statisch analysiert werden, weil jederzeit jemand via `setRelatedCollection` beliebiges reinsetzen könnte?

**Comment by staabm** [comment]
bitte mal ausprobieren: https://github.com/FriendsOfREDAXO/rexstan/pull/408

**Comment by gharlan** [comment]
> ich sehe dort auch `setRelatedCollection`, d.h. müsste dieser setter auch den type erzwingen oder kann `getRelatedCollection` nicht genauer statisch analysiert werden, weil jederzeit jemand via `setRelatedCollection` beliebiges reinsetzen könnte?

`setRelatedCollection` ist mehr eine interne Methode, die man normalerweise nicht selbst aufruft. Die wird von `populateRelation` genutzt.
