### ISSUE TITLE
rex_yform_manager_field implements ArrayAccess

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#409]
**Feature description / Feature Beschreibung**
mir ist aufgefallen dass das `rex_yform_manager_field` dynamische offsets hat.

wie oft arbeitet man mit der klasse und würde es ggf. sinn machen dass rexstan versucht die offsets des arrays zugriffs (und ggf. sogar die value types der offsets) zu kennen/ermitteln?

oder braucht man das nicht?

//cc @gharlan

**Comment by gharlan** [comment]
So ganz einschätzen kann ich es spontan nicht, aber ich glaube eher selten.

Also meine Gefühl ist, dass es sich nicht richtig lohnt, hier etwas zu tun.
