### ISSUE TITLE
Yform: $dataset->getValue() typing

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/rexstan#410]
**Feature description / Feature Beschreibung**

Ähnlich wie in #407 wäre es auch cool, wenn rexstan den Type bei `$dataset->getValue('column')` wüsste.

@tbaddade hatte da zum Beispiel sowas:

```php
class Product extends rex_yform_manager_dataset
{
    public function getTitle(): string {
        // hier meckert rexstan, weil es nicht wissen kann, dass für `title` idR ein String kommt (und nicht etwa int oder so)
        return $this->getValue('title');
    }
}
```

Meist ist `column` also einfach eine Column der Tabelle gemäß Felddefinitionen.
Allerdings können auch zusätzliche Werte im Objekt sein, die per Join o.ä. mit reinkamen.
Der Type hängt somit mit von der Query ab. Es spielt also #382 auch mit rein. Beispiel:

```php
$product = Product::query()
    ->joinRelation('category_id', 'c')
    ->select('c.title', 'category_title') // zusätzliches Feld wird abgefragt
    ->findOne();

$product->getValue('category_title');
```

**Comment by staabm** [comment]
ist hier noch was zu tun?
