### ISSUE TITLE
Update auf 1.0.100 nicht möglich

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/rexstan#414]
<img width="970" alt="Bildschirm­foto 2023-03-19 um 10 50 22" src="https://user-images.githubusercontent.com/330436/226167694-8155fe91-41bf-4f6e-8e5b-aaf6526b45fc.png">

Hmm, hier sind wir jetzt genau bei der befürchteten Situation https://github.com/FriendsOfREDAXO/rexstan/pull/405#issuecomment-1474818967.

Also wir verwenden `RexStanSettings::relativePath` in der install.php, während des Updates gibt es die Methode aber noch nicht.

**Comment by staabm** [comment]
Danke für die info. 

D.h. Das benötigte reparieren wird erst beim update auf 101 passieren, was auch ok ist. 

Ich würde nen method_exists ergänzen, aber sonst können wir nicht viel tun, denke ich

**Comment by gharlan** [comment]
Ja, sollte für den Fall hier passen.
