### ISSUE TITLE
PHP-Pfad muss bei Windows in den Umgebungsvariablen aufgenommen werden

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexstan#42]
Sollte m.E. in den FAQ aufgenommen werden

**Comment by staabm** [comment]
Was genau meinst du ? Mir ist keine windows Besonderheit bei Pfaden bekannt

**Comment by aeberhard** [comment]
Ich habe hier ein XAMPP, die zip-Version. Da wird keine Umgebungsvariable für den Suchpfad für php gesetzt.
Daher kommt bei der Analyse folgender Fehler
![image](https://user-images.githubusercontent.com/330560/176413740-32515f50-547f-42dd-b494-20968d6eb26e.png)

Wenn man den Pfad zur PHP-Exe in der Umgebungsvariable **Path** dazupackt dann passt alles.

**Comment by aeberhard** [comment]
Also die Windows-User-Umgebungsvariablen sind gemeint.

**Comment by staabm** [comment]
Ok danke. Ich denke das sollte in der install routine geprüft werden und mit entsprechendem error und hilfestellungen kenntlich gemacht. 

Auch unter linux/macOs kann das passieren

**Comment by staabm** [comment]
gerne feedback zum neuen release. es sollte jetzt bei installation erkannt werden dass der php-cli command fehlt

**Comment by aeberhard** [comment]
Hi Markus, hab gerade eben getestet. Wie erwartet kam die Fehlermeldung schon beim installieren. Super!
