### ISSUE TITLE
Baseline errors zählen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#430]
**Feature description / Feature Beschreibung**

In erfolgsmeldungen zum level aufstieg die anzahl der baseline errors erwähnen

**Comment by gharlan** [comment]
👍 Wobei es mir auch um diesen Screen vor allem ging:

<img width="967" alt="Bildschirm­foto 2023-03-23 um 08 30 11" src="https://user-images.githubusercontent.com/330436/227133843-a082cead-a173-4d09-b257-2a104fc7923e.png">

Dort vor allem auch um den Satz "In den Einstellungen solltest du jetzt das nächste Level anvisieren.". Da könnte man irgendwie ergänzen "oder die X Baseline-Errors angehen" (wie auch immer man es genau formuliert).
