### ISSUE TITLE
rex_yform_manager_dataset magic properties

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#436]
**Feature description / Feature Beschreibung**
rex_yform_manager_dataset implementiert [magic getter/setter](https://github.com/yakamara/redaxo_yform/blob/01747ff994737fe33c212dd7048ae5d6e24c9901/plugins/manager/lib/yform/manager/dataset.php#L658-L677)

können wir erkennen welche properties ein objekt hat sodass wir probleme wie 

```
		-
			message: "#^Access to an undefined property Model\\\\News\\:\\:\\$image\\.$#"
			count: 1
			path: ../../../../src/addons/project/lib/Model/News.php

		-
			message: "#^Access to an undefined property Model\\\\News\\:\\:\\$publish_date\\.$#"
			count: 3
			path: ../../../../src/addons/project/lib/Model/News.php
```

abstellen können?

mögliche lösung: https://phpstan.org/developing-extensions/class-reflection-extensions

**Comment by staabm** [comment]
@gharlan hier ein anderer yform use-case den ich aus dem kaffeesatz der redaxo.org baseline gelesen hab.
macht das für dich sinn? hast du ideen wie ich ermitteln könnte welche properties welche dataset klasse magisch bereitstellt?

**Comment by gharlan** [comment]
Da die Magic-Getter ja über `getValue` gehen, ist es letztlich das Gleiche wie https://github.com/FriendsOfREDAXO/rexstan/issues/410, denke ich.
Also wenn das andere Ticket gelöst wäre, wüsstest du hier auch, welche magic Properties es gibt.
