### ISSUE TITLE
yakme dir layout: module/templates always true/false errors

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#437]
**Feature description / Feature Beschreibung**

bei verwendung des yakme directory layouts kommen false-positives wg. rex-vars, die wir im [normalen directory layout bereits ignorieren](https://github.com/FriendsOfREDAXO/rexstan/blob/cee0f7413541b5efc41206ba02d9be1cbb4a6738/default-config.neon#L25-L36)

```
	-
			message: "#^Left side of && is always true\\.$#"
			count: 1
			path: "../../../../src/modules/200 - Vertikale Tabs - (Bsp. Funktionsuebersicht)/output.php"

		-
			message: "#^Right side of && is always true\\.$#"
			count: 1
			path: "../../../../src/modules/200 - Vertikale Tabs - (Bsp. Funktionsuebersicht)/output.php"
```

@gharlan ist im yakme layout der pfad immer `/src/modules/` und `/src/templates/`?

**Comment by gharlan** [comment]
> @gharlan ist im yakme layout der pfad immer `/src/modules/` und `/src/templates/`?

Ich denke ja. Also bei uns sind sie immer dort, und ich vermute auch bei allen anderen, die das Dir-Layout nutzen.
(Also mir sind bisher keine Abwandlungen bekannt)
