### ISSUE TITLE
Fehler bei WebUI

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/rexstan#44]
PHP Warning: Unsupported declare 'strict_types' in /volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan on line 3

Warning: Unsupported declare 'strict_types' in /volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan on line 3
PHP Warning: Unsupported declare 'strict_types' in phar:///volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan on line 3

Warning: Unsupported declare 'strict_types' in phar:///volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan on line 3
PHP Parse error: syntax error, unexpected ':', expecting '{' in phar:///volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan on line 67

Parse error: syntax error, unexpected ':', expecting '{' in phar:///volume1/web/sub_web1/redaxo/src/addons/rexstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan on line 67

**Comment by staabm** [comment]
hmm klingt nach einer sehr alten PHP Version? ggf. ist in der CLI auch nicht die korrekte php version eingestellt.

es müsste mindestens php 7.2 sein

**Comment by iceman-fx** [comment]
Alles klar. Verstanden.

Ich habe es auf meiner Synology Nas laufen, da auf meinen Hostingaccounts kein SSH oder exec freigegeben ist.
Wisst ihr zufällig, wie man es denn per SSH prüfen kann, was da für eine PHP Version im System läuft?

**Comment by staabm** [comment]
`php -v` eingeben

**Comment by iceman-fx** [comment]
Zur Info ... auf einem anderen System kommt dies:
PHP Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.2.34-nmm5. in /www/htdocs/xxxxxxx/rexstan.domain.com/redaxo/src/addons/rexstan/vendor/composer/platform_check.php on line 24

**Comment by staabm** [comment]
php 7.3 ist die kleinste noch gepflegte version von php:
https://www.php.net/supported-versions.php

**Comment by staabm** [comment]
die fehler sollten jetzt im aktuellen release nicht mehr passieren.. mindestversion ist jetzt php 7.3.. d.h. auf den systemen wo du bisher die fehler gesehen hast, solltest du zukünftig eine ordentliche fehlermeldung sehen (aber nutzen kannst du es auf diesen systemen wg. zu alter php version trotzdem nicht).
