### ISSUE TITLE
Permission denied // V 1.0.21

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/rexstan#45]
Ich habe gerade das Update der vorletzten Version auf die aktuelle Version (1.0.21) gemacht.
Jetzt erhalte ich:

![image](https://user-images.githubusercontent.com/330516/176618007-549af31f-93e0-4bdc-98ec-4817307c9795.png)

Mit der vorherigen Version funktioniert es.

**Comment by staabm** [comment]
hm interessant.. daran hat sich eigentlich nix geändert

hast du das update ausm installer gezogen? hilft re-install?

**Comment by staabm** [comment]
wie hast du es im terminal aufgerufen?

**Comment by olien** [comment]
Wie im ersten Bild. Jetzt kann ich es ja nicht mehr installieren und testen in dem Projekt...
