### ISSUE TITLE
Project Linting hohe CPU-Last unter Windows - Abbruch max_execution time

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexstan#472]
Linting läuft ewig und CPU ist auf 100% bricht dann ab wg. max_execution_time

Da werden doch nur die `package.yml` geprüft?

Liegt bei mir wahrscheinlich auch am McAffe/Trellix der sich mit PHP-CLI um die CPU streitet.

**Comment by staabm** [comment]
Das linting erzeugt viele prozesse und wird langsam bei sehr großen installationen. 

Ggf. Sollten wir es einschränken auf die AddOns die in den rexsettings hinterlegt sind, damit es schneller wird

**Comment by staabm** [comment]
Linting wird mit PHP 8.3+ hoffentlich schneller

https://github.com/php/php-src/issues/10024

**Comment by staabm** [comment]
Besser mit dem aktuellen release @aeberhard ?

**Comment by aeberhard** [comment]
Sehr viel besser @staabm :) 👍
