### ISSUE TITLE
Anführungszeichen in sql query erzeugen einen Fehler

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/rexstan#493]
Folgender Query
```
$sqlDelete->prepareQuery('UPDATE rex_yf_jobs SET export ="" WHERE export !="" ');
```
erzeugen den Fehler `Unable to resolve column ''`

Maskierte Anführungszeichen laufen ohne Fehler durch:
```
$sqlDelete->prepareQuery('UPDATE rex_yf_jobs SET export = \'\' WHERE export != \'\'');
```

**Comment by staabm** [comment]
kann ich bei mir nicht nachvollziehen. ist der fehler reproduzierbar?

**Comment by marcohanke** [comment]
Ich muss noch mal schauen wo das war. Vielleicht hat sich das mit einem der letzten 140 Updates auch erledigt ;-)

**Comment by marcohanke** [comment]
Okay, ich war mal wieder zu fahrig. Der Fehler kommt aus PHPStorm. Sorry
