### ISSUE TITLE
Could not get PHP version from CLI

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/rexstan#501]
**Description / Beschreibung**

Whoopps beim Aufruf 

![image](https://github.com/FriendsOfREDAXO/rexstan/assets/330516/2248a9fd-1f05-4467-ba1d-7a9b7b2878c7)

**Affected versions / Verwendete Versionen**

<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.0, MySQL 5.7.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.39 |
| Character set | utf8mb4      |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.54 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.4 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                  |            |
| ------------------------: | :--------- |
|              accessdenied | 2.0.2      |
|                   adminer | 1.9.3      |
|                    backup | 2.9.0      |
|                  be_style | 3.2.0      |
|       be_style/customizer | 3.2.0      |
|           be_style/redaxo | 3.2.0      |
|                   bloecks | 3.1.1      |
|          bloecks/cutncopy | 3.1.1      |
|                   cronjob | 2.10.0     |
|                 developer | 3.9.2      |
|                focuspoint | 4.0.4      |
|                 gridblock | 1.1.8      |
| gridblock/contentsettings | 1.7.0      |
|    gridblock/synchronizer | 1.0        |
|                   install | 2.11.1     |
|                    mblock | 3.4.12     |
|             media_manager | 2.14.0     |
|          media_negotiator | 2.0.0      |
|                 mediapool | 2.13.0     |
|                  metainfo | 2.10.0     |
|                     mform | 7.2.8      |
|          navigation_array | 1.2.1      |
|                 phpmailer | 2.12.0     |
|                   project | dev        |
|          quick_navigation | 6.0.2      |
|                  redactor | 2.3.0      |
|                 rexfactor | 0.1.6      |
|                   rexstan | 1.0.111    |
|                     sprog | 1.5.1      |
|                 structure | 2.15.0     |
|         structure/content | 2.15.0     |
|                     theme | 1.4.0      |
|                  uploader | 2.4.1      |
|                       url | 2.1.0      |
|                     users | 2.10.0     |
|                     yform | 4.1.1      |
|               yform/email | 4.1.1      |
|             yform/manager | 4.1.1      |
|               yform/tools | 4.1.1      |
|    yform_flexible_content | 0.0.1-dev  |
|     yform_spam_protection | 1.2.3      |
|                  yrewrite | 2.10.0     |

</details>

REDAXO:  5.15.1
PHP: 8.2.0
Database: MySQL 5.7.39

owser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**RuntimeException:** Could not get PHP version from CLI: sh: php: command not found

**File:** redaxo/src/addons/rexstan/lib/RexPhpVersion.php
**Line:** 22

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                              | Line     |
| -------------------------------------------- | ------------------------------------------------- | -------- |
| rexstan\RexPhpVersion::getCliVersion         | redaxo/src/addons/rexstan/lib/RexStanSettings.php | 101      |
| rexstan\RexStanSettings::createForm          | redaxo/src/addons/rexstan/pages/settings.php      | 6        |
| require                                      | redaxo/src/core/lib/packages/package.php          | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php             | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                | 62       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php             | 485      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php             | 453      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/rexstan/pages/index.php         | 24       |
| require                                      | redaxo/src/core/lib/packages/package.php          | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php             | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                | 62       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php             | 485      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php             | 436      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                       | 241      |
| require                                      | redaxo/src/core/boot.php                          | 155      |
| require                                      | redaxo/index.php                                  | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.0, MySQL 5.7.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.39 |
| Character set | utf8mb4      |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.54 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.4 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                  |            |
| ------------------------: | :--------- |
|              accessdenied | 2.0.2      |
|                   adminer | 1.9.3      |
|                    backup | 2.9.0      |
|                  be_style | 3.2.0      |
|       be_style/customizer | 3.2.0      |
|           be_style/redaxo | 3.2.0      |
|                   bloecks | 3.1.1      |
|          bloecks/cutncopy | 3.1.1      |
|                   cronjob | 2.10.0     |
|                 developer | 3.9.2      |
|                focuspoint | 4.0.4      |
|                 gridblock | 1.1.8      |
| gridblock/contentsettings | 1.7.0      |
|    gridblock/synchronizer | 1.0        |
|                   install | 2.11.1     |
|                    mblock | 3.4.12     |
|             media_manager | 2.14.0     |
|          media_negotiator | 2.0.0      |
|                 mediapool | 2.13.0     |
|                  metainfo | 2.10.0     |
|                     mform | 7.2.8      |
|          navigation_array | 1.2.1      |
|                 phpmailer | 2.12.0     |
|                   project | dev        |
|          quick_navigation | 6.0.2      |
|                  redactor | 2.3.0      |
|                 rexfactor | 0.1.6      |
|                   rexstan | 1.0.111    |
|                     sprog | 1.5.1      |
|                 structure | 2.15.0     |
|         structure/content | 2.15.0     |
|                     theme | 1.4.0      |
|                  uploader | 2.4.1      |
|                       url | 2.1.0      |
|                     users | 2.10.0     |
|                     yform | 4.1.1      |
|               yform/email | 4.1.1      |
|             yform/manager | 4.1.1      |
|               yform/tools | 4.1.1      |
|    yform_flexible_content | 0.0.1-dev  |
|     yform_spam_protection | 1.2.3      |
|                  yrewrite | 2.10.0     |

</details>

**Comment by aeberhard** [comment]
Da fehlt dir PHP im Suchpfad! $PATH auf Windows, aufm MAC leider keine Ahnung

**Comment by aeberhard** [comment]
@olien schau mal bei den closed issues

**Comment by olien** [comment]
@aeberhard danke. hatte ich. hab keine Lösung gefunden. ich glaub das Problem gab es auch schonmal und wurde gefixt...

**Comment by staabm** [comment]
jop, der fehler bedeutet dass auf deinem server/system entweder gar kein php in der CLI installiert ist, oder es nicht im %PATH% gefunden wird. so wie es andreas beschreibt.

entweder du redest mit deinem hoster (falls es ein server ist) oder lieferst mehr infos über das system

**Comment by olien** [comment]
Ist lokal. Hattest du ja schonmal geguckt (hab vergessen, dass es das war). Ist dann halt so.. alles ok

**Comment by staabm** [comment]
hat es auf dem system schonmal funktioniert oder ist das noch immer das gleiche problem wie schon damals und es hat noch nie funktioniert?

**Comment by staabm** [comment]
wenn man PHP auf dem mac nach folgender Anleitung installiert, hat es meiner Erfahrung nach sehr gut funktioniert:

https://getgrav.org/blog/macos-ventura-apache-multiple-php-versions
