### ISSUE TITLE
CLI-PHP fälschlich nicht erkannt

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#543]
**Description / Beschreibung**

Auf einem ansonsten schon immer funktionierenden Redaxo-System mit RexStan habe ich fahrlässig RexStan in der Addon-Verwaltung re-installiert. Das ergab zu meiner großen Überraschung den Fehler:

> AddOn rexstan konnte aus folgendem Grund nicht installiert werden:
> Unable to determine PHP CLI version. Make sure PHP is installed in the CLI and availabe within your system PATH. 

Kann nicht sein! Ich hab mir die Code-Stelle rausgesucht und zusätzlichen Test-Code eingebaut:

Original:
https://github.com/FriendsOfREDAXO/rexstan/blob/742b6b99fbc26fd3481ce7429cc3dfde35112304/lib/RexCmd.php#L87-L96

Mit Test-Code:
```php
public static function getCliPhpVersion(): ?string
{
    $cliPhpVersion = self::execCmd(self::phpExecutable().' -r "echo PHP_VERSION_ID;"', $stderrOutput, $exitCode);

    $result = shell_exec('php -r "echo PHP_VERSION_ID;"');
    dd(get_defined_vars());

    if (is_numeric($cliPhpVersion)) {
        return $cliPhpVersion;
    }

    return null;
}
```
Nun erhalte ich bei "Installieren" diesen Dump:
```
^ array:4 [▼
    "cliPhpVersion" => ""
    "stderrOutput" => ""
    "exitCode" => -1
    "result" => "80208"
]
```
Wie man an der letzten Zeile sieht, liefert die Shell sehr wohl ein posiives Ergebnis. CLI_PHP ist verfügbar.

Wechsel der CLI_PHP-Version und System-Neustart ändert nichts. Ebenso wenig Löschen des Redaxo-Cache.

**Affected versions / Verwendete Versionen**
Redaxo 5.15.1
SAPI-PHP: 8.2.8
CLI-PHP: 8.2.8
RexStan 1.0.121 (ist aber mit älteren Versionen genauso, z.B. mit einer 1.0.107 in einer anderen Instanz)
iMac mit BigSur

**Comment by staabm** [comment]
danke für den report.

könntest du weiter debuggen was in `self::execCmd` ausgeführt wird und für deinen server dann dort nicht passt?

**Comment by christophboecker** [comment]
Das muss ich jetzt aber nicht verstehen ... Mehrere Dump eingebaut. Plötzlich ist das korrekte Ergebnis da. Dumps wieder raus, klappt immer noch.

Ich mach wieder zu und melde mich, wenn das "Phänomen" wieder auftritt.
