### ISSUE TITLE
Class XY extends unknown class PHPUnit\Framework\TestCase.

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#69]
bei der analyse von zum beispiel core addons die unit tests enhalten kommt die Fehlermeldung

> Class rex_managed_media_test extends unknown class PHPUnit\Framework\TestCase.

das liegt daran dass redaxo selbst nur eine require-dev abhägigkeit zu phpunit hat.

**Comment by gharlan** [comment]
Wobei im Release die Unittests doch gar nicht enthalten sind, oder?
Hat man das Problem nicht nur, wenn man den Core über git auscheckt? Und da müsste man dann `composer install` ausführen, und rexstan müsste dann den autoloader vom root composer mit berücksichtigen.

**Comment by staabm** [comment]
wenn ich in der `phpstan-bootstrap.php` einen include auf den root composer autoloader einfüge

```
if(is_file(rex_path::base('vendor/autoload.php'))) {
    require_once rex_path::base('vendor/autoload.php');
}
```

bekomme ich errors re-declare errors
```
➜  rexstan git:(main) ✗ pwd
/Users/staabm/workspace/redaxo/redaxo/src/addons/rexstan
➜  rexstan git:(main) ✗ php phpstan-bootstrap.php
PHP Fatal error:  Cannot redeclare rex_escape() (previously declared in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php:33) in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php on line 33
Cannot redeclare rex_escape() (previously declared in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php:33)

Fatal error: Cannot redeclare rex_escape() (previously declared in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php:33) in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php on line 33
ErrorException: Cannot redeclare rex_escape() (previously declared in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php:33) in /Users/staabm/workspace/redaxo/redaxo/src/core/functions/function_rex_escape.php:33
Stack trace:
#0 [internal function]: rex_error_handler::shutdown()
#1 {main}%
```

**Comment by gharlan** [comment]
Hmm. Frage mich, wie es im aktuellen phpstan-Setup im core-repo funktioniert. Für das console-plugin wird REDAXO auch gebootet: https://github.com/redaxo/redaxo/blob/main/.tools/phpstan/console.php#L10. Aber der root-autoloader müsste doch eigentlich auch greifen, oder?

**Comment by staabm** [comment]
wenn phpstan im project root ausgeführt wird und der composer vendor/ auch im project root liegt, scheint es ein paar auto-magische dinge zu geben, die phpstan mit dem composer autoloader besser zusammen arbeiten lassen.

https://github.com/phpstan/phpstan/issues/7732 ist ähnlich gelagert
