### ISSUE TITLE
`$value of function strval expects bool|float|int|resource|string|null, mixed given.`

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/rexstan#730]
**Description / Beschreibung**
Parameter #1 $value of function strval expects bool|float|int|resource|string|null, mixed given.

Diese Meldung scheint falsch zu sein, laut PHP-Doku:

<https://www.php.net/manual/en/function.strval.php>

> strval([mixed](https://www.php.net/manual/en/language.types.mixed.php) $value): [string](https://www.php.net/manual/en/language.types.string.php)

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by staabm** [comment]
ich vermute das ist ein duplicate von https://github.com/phpstan/phpstan/issues/9295#issuecomment-1542186125
