### ISSUE TITLE
php not found

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexstan#74]
mamp user haben das problem dass php nicht im pfad ist.
Oftmals sind diese user auch nicht in der lage php in den $PATH zu bringen

man könnte überlegen statt dem error
https://github.com/FriendsOfREDAXO/rexstan/blob/0f6c5c7e6e7bb4eb8f7eb3cac4f9f747c2c64dbe/install.php#L18
Eine möglichkeit anzubieten dass man in rexstan den pfad zur php-cli hinterlegen kann

**Comment by staabm** [comment]
ggf. können wir den pfad von mamp finden mittels https://stackoverflow.com/a/29990624/1597388

**Comment by skerbis** [comment]
Eine manuelle Eingabe wäre gut. So könnte man auch auf plesk systemen einen geeigneten Interpreter abseits des os php auswählen. Häufig haben die linux distros veraltete php Versionen aber Plesk liefert alle aktuellen auch für das cli

**Comment by staabm** [comment]
Kann man die php pfade aus plesk auch irgendwie auslesen? Sind die fix?

**Comment by staabm** [comment]
Vllt finden wir auch hier irgendwo die logik wie plesk die php versionen findet
https://github.com/plesk/

**Comment by skerbis** [comment]
Nein. Plesk liefert zwar Interpreter an meldet diese aber nicht global an. 
php -v liefert immer die vom OS, sofern installier
/opt/plesk/php/7.4/bin/php -v  die von php 7.4
/opt/plesk/php/8.1/bin/php -v  die von php 8.1
usw.

**Comment by staabm** [comment]
fixed mit https://github.com/FriendsOfREDAXO/rexstan/pull/174

oder brauchen wir für plesk ähnliche workarounds?

**Comment by skerbis** [comment]
In Plesk ist es immer folgendes Schema: 
/opt/plesk/php/8.1/bin/php ...
was muss ich nun tun um es anzumelden?

**Comment by staabm** [comment]
Reicht dir die mamp php version erkennung um es analog für plesk zu realisieren?

https://github.com/FriendsOfREDAXO/rexstan/pull/174/files

**Comment by skerbis** [comment]
am liebsten würde ich einfach nur den Pfad setzen können. Es gibt keine Config oder ähnliches wo das Web reinschauen und  suchen kann

**Comment by skerbis** [comment]
wo kommt die Konstante PHP_MAJOR_VERSION her?

**Comment by staabm** [comment]
Die bringt der php prozess im apache mit

**Comment by skerbis** [comment]
und ich vom cli php interpreter

**Comment by christophboecker** [comment]
https://www.php.net/manual/en/reserved.constants.php

**Comment by staabm** [comment]
> und ich vom cli php interpreter
das kann ein anderer sein

Ich präzisiere: ich rede davon wie/wo rexstan die php cli version findet um diesen in der weboberfläche im backend für die analyse zu verwenden

Wenn du aus der cli heraus rexstan aufrufen willst, kannst du ja bereits mit `pfad/zu/php redaxo/console rexstan:analyze` die php version selbst mitgeben
