### ISSUE TITLE
Frage: gegen welche PHP-Versionen kann rex/phpstan prüfen

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#84]
Kann man programmatisch abfragen - und wenn ja, wie - welche PHP-Versionen als `phpVersion: xxxxxx` einstellbar sind? Also was phpstan unterstützt? Ich hab noch nichts dazu gefunden.

**Comment by staabm** [comment]
es sind alle php versionen einstellbar inkl. minor version. ich würde dem user aber nur die auswahl geben 7.3/7.4/8.0/8.1/8.2

**Comment by christophboecker** [comment]
Das ist mir klar. Ich würde nur gerne irgendwo automatisch abfragen können, welche x.y-Versionen es für phpstan gibt, dann alle vor der Redaxo-Mindestversion rauswerfen und den Rest anbieten. Fest verdrahtet nehme ich nur ungerne, wenn es auch dynamische Lösungen gibt.

**Comment by staabm** [comment]
die liste diese versionen ändert sich einmal in 1-2 jahren. daher würde ich die hard kodieren.
das addon bietet ohnehin ständig updates (z.b. wg. phpstan updates).. daher seh ich da kein problem.

dein screenshot sieht super aus

**Comment by christophboecker** [comment]
Dann von Hand. Bei der Frequenz lohnt das Nachdenken nicht.
