### ISSUE TITLE
Frage: beim Finetuning des Codes namespace noch mal anpassen?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#86]
Was mir im Code auffiel:

```php
namespace redaxo\phpstan;
```

Spontan hätte ich erwartet dass der Namespace rexstan heißt, sich also zumindest etwas an der Verzeichnisstruktur anlehnt
```php
namespace redaxo\rexstan;
```

Scheint ja keine funktional erkennbaren Auswirkungen zu haben. Vielleicht hieß das Addon ja auch mal phpstan und der namespace ist noch nicht nachgezogen? Nur so als Frage oder Merker. Kann auch gerne ignorieren

**Comment by staabm** [comment]
Stimmt. Ich hatte die extensions urspr. Direkt in redaxo core entwickelt und später hier reinverschoben

**Comment by christophboecker** [comment]
Wie sollte der Namespave denn lauten? Einfach "rexstan"? Oder "redaxo/rexstan"? Oder ....?

**Comment by staabm** [comment]
nur `rexstan`

**Comment by christophboecker** [comment]
Ich wollte das grade ändern, laufe aber auf ein für mich nicht lösbares Problem:

In `.../lib/RexClassDynamicReturnTypeExtension.php` ändere ich den Namespace in `namespace Rexstan;` und in der einzigen Datei, die darauf verweist (`default-config.neon`) den Verweis in Zeile 88 in `class: rexstan\RexClassDynamicReturnTypeExtension`.

Die Analyse ergibt dann den Fehler:
<img width="1472" alt="grafik" src="https://user-images.githubusercontent.com/10065904/189489169-7b22e1e7-91f4-4eb1-bd23-3f96ffbc293d.png">

Egal was ich ausprobiere, nur mit dem Namespace `redaxo\phpstan` läuft es. Ich vermute ein Cache-Problem, habe schon den Redaxo-Cache und autoload-Cache gelöscht sowie den phpstan-Result-Cache. Alles ohne Wirkung.

PS: Das gleiche Problem mit `RexFunctionsDynamicReturnTypeExtension.php`.

ich höre hier erstmal auf. Hat ja keine Prio.
