### ISSUE TITLE
Frage: lang-Dateien nutzen?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/rexstan#87]
Sollen perspektivisch die Texte aus den Formularen etc. konsequent über lang-Dateien verwaltet werden? Wenn ja könnte das ja auch mal ein kleiner PR werden? "Good First PR" oder so.

**Comment by staabm** [comment]
Wegen mir gerne. Ich denke aber eher low prio, da wir primär die idee und den workflow mit dem addon zunächst optimieren sollten. 

Ich gehe davon aus dass es aktuell zu 99% von deutsch sprachigen verwendet wird

**Comment by staabm** [comment]
aktuell eher nein
